<a href="https://colab.research.google.com/github/eteitelbaum/code-satp/blob/main/model-data-size-experiments/action_type/exp_actiontype.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install transformers datasets torch scikit-learn

Requirement already satisfied: transformers in /usr/local/lib/python3.11/dist-packages (4.48.3)
Collecting datasets
  Downloading datasets-3.4.0-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: torch in /usr/local/lib/python3.11/dist-packages (2.6.0+cu124)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.11/dist-packages (1.6.1)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from transformers) (3.17.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.24.0 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.28.1)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.11/dist-packages (from transformers) (1.26.4)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from transformers) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from transformers) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.11/dist-packages (from transformers) (2024.11.6)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from transformers) (2.32.3)
Requirement already satisfied: tokenizers<0.22,>=0.21 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.21.0)
Requirement already satisfied: safetensors>=0.4.1 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.5.3)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.11/dist-packages (from transformers) (4.67.1)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.11/dist-packages (from datasets) (18.1.0)
Collecting dill<0.3.9,>=0.3.0 (from datasets)
  Downloading dill-0.3.8-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (from datasets) (2.2.2)
Collecting xxhash (from datasets)
  Downloading xxhash-3.5.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (12 kB)
Collecting multiprocess<0.70.17 (from datasets)
  Downloading multiprocess-0.70.16-py311-none-any.whl.metadata (7.2 kB)
Requirement already satisfied: fsspec<=2024.12.0,>=2023.1.0 in /usr/local/lib/python3.11/dist-packages (from fsspec[http]<=2024.12.0,>=2023.1.0->datasets) (2024.10.0)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.11/dist-packages (from datasets) (3.11.13)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.11/dist-packages (from torch) (4.12.2)
Requirement already satisfied: networkx in /usr/local/lib/python3.11/dist-packages (from torch) (3.4.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from torch) (3.1.6)
Collecting nvidia-cuda-nvrtc-cu12==12.4.127 (from torch)
  Downloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-runtime-cu12==12.4.127 (from torch)
  Downloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-cupti-cu12==12.4.127 (from torch)
  Downloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cudnn-cu12==9.1.0.70 (from torch)
  Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cublas-cu12==12.4.5.8 (from torch)
  Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cufft-cu12==11.2.1.3 (from torch)
  Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-curand-cu12==10.3.5.147 (from torch)
  Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cusolver-cu12==11.6.1.9 (from torch)
  Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cusparse-cu12==12.3.1.170 (from torch)
  Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Requirement already satisfied: nvidia-cusparselt-cu12==0.6.2 in /usr/local/lib/python3.11/dist-packages (from torch) (0.6.2)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /usr/local/lib/python3.11/dist-packages (from torch) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch) (12.4.127)
Collecting nvidia-nvjitlink-cu12==12.4.127 (from torch)
  Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Requirement already satisfied: triton==3.2.0 in /usr/local/lib/python3.11/dist-packages (from torch) (3.2.0)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.11/dist-packages (from torch) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from sympy==1.13.1->torch) (1.3.0)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn) (1.14.1)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn) (3.5.0)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (1.3.2)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (25.2.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (1.5.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (6.1.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (0.3.0)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (1.18.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (2025.1.31)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->torch) (3.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets) (2025.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Downloading datasets-3.4.0-py3-none-any.whl (487 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 487.4/487.4 kB 21.5 MB/s eta 0:00:00
Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl (363.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 3.2 MB/s eta 0:00:00
Downloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (13.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 19.6 MB/s eta 0:00:00
Downloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (24.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 16.8 MB/s eta 0:00:00
Downloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (883 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 25.1 MB/s eta 0:00:00
Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl (664.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 2.9 MB/s eta 0:00:00
Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl (211.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 2.4 MB/s eta 0:00:00
Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl (56.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 9.7 MB/s eta 0:00:00
Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl (127.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 8.2 MB/s eta 0:00:00
Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl (207.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 4.8 MB/s eta 0:00:00
Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (21.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 28.1 MB/s eta 0:00:00
Downloading dill-0.3.8-py3-none-any.whl (116 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 kB 5.0 MB/s eta 0:00:00
Downloading multiprocess-0.70.16-py311-none-any.whl (143 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 143.5/143.5 kB 11.1 MB/s eta 0:00:00
Downloading xxhash-3.5.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (194 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.8/194.8 kB 11.5 MB/s eta 0:00:00
Installing collected packages: xxhash, nvidia-nvjitlink-cu12, nvidia-curand-cu12, nvidia-cufft-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, dill, nvidia-cusparse-cu12, nvidia-cudnn-cu12, multiprocess, nvidia-cusolver-cu12, datasets
  Attempting uninstall: nvidia-nvjitlink-cu12
    Found existing installation: nvidia-nvjitlink-cu12 12.5.82
    Uninstalling nvidia-nvjitlink-cu12-12.5.82:
      Successfully uninstalled nvidia-nvjitlink-cu12-12.5.82
  Attempting uninstall: nvidia-curand-cu12
    Found existing installation: nvidia-curand-cu12 10.3.6.82
    Uninstalling nvidia-curand-cu12-10.3.6.82:
      Successfully uninstalled nvidia-curand-cu12-10.3.6.82
  Attempting uninstall: nvidia-cufft-cu12
    Found existing installation: nvidia-cufft-cu12 11.2.3.61
    Uninstalling nvidia-cufft-cu12-11.2.3.61:
      Successfully uninstalled nvidia-cufft-cu12-11.2.3.61
  Attempting uninstall: nvidia-cuda-runtime-cu12
    Found existing installation: nvidia-cuda-runtime-cu12 12.5.82
    Uninstalling nvidia-cuda-runtime-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-runtime-cu12-12.5.82
  Attempting uninstall: nvidia-cuda-nvrtc-cu12
    Found existing installation: nvidia-cuda-nvrtc-cu12 12.5.82
    Uninstalling nvidia-cuda-nvrtc-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-nvrtc-cu12-12.5.82
  Attempting uninstall: nvidia-cuda-cupti-cu12
    Found existing installation: nvidia-cuda-cupti-cu12 12.5.82
    Uninstalling nvidia-cuda-cupti-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-cupti-cu12-12.5.82
  Attempting uninstall: nvidia-cublas-cu12
    Found existing installation: nvidia-cublas-cu12 12.5.3.2
    Uninstalling nvidia-cublas-cu12-12.5.3.2:
      Successfully uninstalled nvidia-cublas-cu12-12.5.3.2
  Attempting uninstall: nvidia-cusparse-cu12
    Found existing installation: nvidia-cusparse-cu12 12.5.1.3
    Uninstalling nvidia-cusparse-cu12-12.5.1.3:
      Successfully uninstalled nvidia-cusparse-cu12-12.5.1.3
  Attempting uninstall: nvidia-cudnn-cu12
    Found existing installation: nvidia-cudnn-cu12 9.3.0.75
    Uninstalling nvidia-cudnn-cu12-9.3.0.75:
      Successfully uninstalled nvidia-cudnn-cu12-9.3.0.75
  Attempting uninstall: nvidia-cusolver-cu12
    Found existing installation: nvidia-cusolver-cu12 11.6.3.83
    Uninstalling nvidia-cusolver-cu12-11.6.3.83:
      Successfully uninstalled nvidia-cusolver-cu12-11.6.3.83
Successfully installed datasets-3.4.0 dill-0.3.8 multiprocess-0.70.16 nvidia-cublas-cu12-12.4.5.8 nvidia-cuda-cupti-cu12-12.4.127 nvidia-cuda-nvrtc-cu12-12.4.127 nvidia-cuda-runtime-cu12-12.4.127 nvidia-cudnn-cu12-9.1.0.70 nvidia-cufft-cu12-11.2.1.3 nvidia-curand-cu12-10.3.5.147 nvidia-cusolver-cu12-11.6.1.9 nvidia-cusparse-cu12-12.3.1.170 nvidia-nvjitlink-cu12-12.4.127 xxhash-3.5.0

In [ ]:
# def compute_metrics(eval_pred):
#     logits, labels = eval_pred
#     predictions = (torch.sigmoid(torch.tensor(logits)) > 0.5).numpy()  # Apply threshold
#     labels = labels.astype(int)

#     hamming = hamming_loss(labels, predictions)
#     subset_acc = accuracy_score(labels, predictions)
#     report = classification_report(labels, predictions, output_dict=True, zero_division=0)

#     return {
#         "hamming_loss": hamming,
#         "subset_accuracy": subset_acc,
#         "precision_micro": report["micro avg"]["precision"],
#         "recall_micro": report["micro avg"]["recall"],
#         "f1_micro": report["micro avg"]["f1-score"],
#     }

In [ ]:
import torch
from torch.utils.data import Dataset
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, hamming_loss, accuracy_score
from transformers import AutoTokenizer, AutoModelForSequenceClassification, Trainer, TrainingArguments

# =======================
# Generalized Dataset Class
# =======================
class MultiLabelDataset(Dataset):
    def __init__(self, texts, labels, tokenizer, max_len):
        self.texts = texts
        self.labels = labels
        self.tokenizer = tokenizer
        self.max_len = max_len

    def __len__(self):
        return len(self.texts)

    def __getitem__(self, idx):
        text = self.texts[idx]
        label = self.labels[idx]
        encoding = self.tokenizer(
            text,
            max_length=self.max_len,
            padding="max_length",
            truncation=True,
            return_tensors="pt",
        )
        return {
            "input_ids": encoding["input_ids"].squeeze(0),
            "attention_mask": encoding["attention_mask"].squeeze(0),
            "labels": torch.tensor(label, dtype=torch.float),
        }

# =======================
# Function to Compute Metrics
# =======================


from sklearn.metrics import classification_report, hamming_loss, accuracy_score

def compute_metricss(eval_pred):
    """
    Compute evaluation metrics for multi-label classification.
    Includes Hamming Loss, Subset Accuracy, and Classification Report for all labels.
    """
    logits, labels = eval_pred
    predictions = (torch.sigmoid(torch.tensor(logits)) > 0.5).numpy()  # Apply threshold
    labels = labels.astype(int)

    # Hamming Loss
    hamming = hamming_loss(labels, predictions)

    # Subset Accuracy
    subset_acc = accuracy_score(labels, predictions)

    # Classification Report
    report = classification_report(
        labels, predictions, target_names=data.columns[1:], zero_division=0, output_dict=True
    )

    # Print complete report for reference
    print("\nFull Classification Report:")
    print(classification_report(labels, predictions, target_names=data.columns[:-1], zero_division=0))

    # Summary Metrics for Trainer
    metrics = {
        "hamming_loss": hamming,
        "subset_accuracy": subset_acc,
    }
    metrics.update(report)
    return metrics


# =============================
# Reusable Training Function
# =============================

def train_transformer_model(model_name, data, max_len=512, test_size=0.1, val_size=0.1, batch_size=40, epochs=3):
    """
    Generalized function to train a transformer model for multi-label classification.
    Args:
        model_name: Name of the pre-trained model (e.g., "bert-base-uncased", "distilbert-base-uncased").
        data: Pandas DataFrame with columns "incident_summary" and multi-label columns.
        max_len: Maximum sequence length.
        batch_size: Batch size for training and evaluation.
        epochs: Number of training epochs.
    """
    # Load tokenizer and model
    tokenizer = AutoTokenizer.from_pretrained(model_name)
    model = AutoModelForSequenceClassification.from_pretrained(
        model_name,
        num_labels=data.shape[1] - 1,  # Number of labels (all columns except "incident_summary")
        problem_type="multi_label_classification",
    )
    model.to("cuda" if torch.cuda.is_available() else "cpu")

    # Split data into train, val, and test
    X = data["incident_summary"]
    y = data.drop('incident_summary', axis=1).values

    X_train, X_temp, y_train, y_temp = train_test_split(X, y, test_size=test_size, random_state=42)
    X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=val_size, random_state=42)

    # Create datasets
    train_dataset = MultiLabelDataset(X_train.tolist(), y_train, tokenizer, max_len)
    val_dataset = MultiLabelDataset(X_val.tolist(), y_val, tokenizer, max_len)
    test_dataset = MultiLabelDataset(X_test.tolist(), y_test, tokenizer, max_len)

    # Define training arguments
    training_args = TrainingArguments(
        output_dir="./results",
        evaluation_strategy="epoch",
        save_strategy="epoch",
        learning_rate=2e-5,
        per_device_train_batch_size=batch_size,
        per_device_eval_batch_size=batch_size,
        num_train_epochs=epochs,
        weight_decay=0.01,
        logging_dir="./logs",
        logging_steps=10,
        load_best_model_at_end=True,
        metric_for_best_model='eval_hamming_loss',
        greater_is_better=True,
        save_total_limit=2,
        report_to="none",
    )

    # Initialize Trainer
    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=train_dataset,
        eval_dataset=val_dataset,
        processing_class=tokenizer,
        compute_metrics=compute_metricss,
    )

    # Train and Evaluate
    trainer.train()

    # Final Evaluation on Test Set
    test_results = trainer.evaluate(test_dataset)
    print("Test Set Results:", test_results)

    return trainer, test_results

In [ ]:
fraction_labels = {
    1/32: "3%",   # 1/32 = 3.125%
    1/16: "6%",   # 1/16 = 6.25%
    1/8:  "12%",  # 1/8  = 12.5%
    1/4:  "25%",
    1/2:  "50%",
    1.0:  "100%"
}

model_name_labels = {
    "bert-base-cased": "BERT Base (cased)",
    "snowood1/ConfliBERT-scr-cased": "ConfliBERT-scr-cased",
    "FacebookAI/roberta-base": "RoBERTa Base",
    "distilbert-base-cased": "DistilBERT (cased)",
    "xlnet-base-cased": "XLNet Base (cased)",
    "google/electra-base-discriminator": "ELECTRA Base"
}

fractions = [1/32, 1/16, 1/8, 1/4, 1/2, 1.0]

models_list = [
    "bert-base-cased",
    "snowood1/ConfliBERT-scr-cased",
    "FacebookAI/roberta-base",
    "distilbert-base-cased",
    "xlnet-base-cased",
    "google/electra-base-discriminator"
]

In [ ]:
def run_all_experiments_and_save(df_full, output_csv="experiment_results.csv"):
    """
    1. Iterates over the defined fractions & model list
    2. Samples df_full according to fraction
    3. Trains & evaluates using train_multiclass_model_3way_split
    4. Saves the collected results in a DataFrame
    5. Exports to CSV

    Args:
        df_full (pd.DataFrame): Full dataset with columns [label_col, text_col].
        output_csv (str): File path to save the experiment results.
    Returns:
        results_df (pd.DataFrame): Contains experiment results for analysis.
    """
    results_list = []

    for frac in fractions:
        # Sample a fraction of the data
        subset_size = int(len(df_full) * frac)
        df_subset = df_full.sample(n=subset_size, random_state=42)

        # Friendly fraction label if you want
        frac_label = fraction_labels.get(frac, f"{frac*100:.1f}%")
        print(f"\n=== DATA FRACTION: {frac} ({subset_size} rows) ===")

        for model_name in models_list:
            # Model label
            model_label = model_name_labels.get(model_name, model_name)
            print(f"Training model: {model_label}")

            # Train & evaluate
            # write the model funtion here
            trainer, test_results = train_transformer_model(model_name, df_subset, max_len=512, test_size=0.1, val_size=0.1, batch_size=16, epochs=2)


            # Build a result dict
            run_result = {
                "fraction_raw": frac,
                "fraction_label": frac_label,
                "subset_size": subset_size,
                "model_raw": model_name,
                "model_label": model_label
            }

            # Flatten the nested dictionary
            for key, value in test_results.items():
                if isinstance(value, dict):
                    for subkey, subvalue in value.items():
                        # Create new key names like "armed_assault_precision"
                        run_result[f"{key}_{subkey}"] = subvalue
                else:
                    run_result[key] = value

            # Append to results_list
            results_list.append(run_result)

    # Convert to DataFrame
    results_df = pd.DataFrame(results_list)
    # Save to CSV
    results_df.to_csv(output_csv, index=False)
    print(f"\nResults saved to {output_csv}")

    # also save to JSON
    # results_df.to_json("experiment_results.json", orient="records")

    return results_df

#**Read from GitHub**

In [ ]:
import pandas as pd

# Corrected URL to access the raw CSV data
url = 'https://raw.githubusercontent.com/eteitelbaum/code-satp/main/model-data-size-experiments/action_type/action_type.csv'

try:
    data = pd.read_csv(url)
    print(data.head())
except Exception as e:
    print(f"Error loading CSV from URL: {e}")

  perpetrator                                   incident_summary
0    Security  An alleged arms supplier to the Communist Part...
1      Maoist  A Kamareddy dalam (squad) member belonging to ...
2    Security  Senior CPI-Maoist 'Polit Bureau' and 'central ...
3      Maoist  A TDP leader and former Sarpanch of Jerrela Gr...
4      Maoist  The CPI-Maoist cadres blasted coffee pulping u...

# **Read From Drive**

In [ ]:
import pandas as pd
from google.colab import drive
drive.mount('/content/drive')

data = pd.read_csv('/content/drive/MyDrive/SATP_data/action_type.csv')

# **Loop Exe**

In [ ]:

#
# Example usage:
final_results_df = run_all_experiments_and_save(data, output_csv="experiment_results.csv")

# Now you can inspect final_results_df in Python:
print(final_results_df.head())

# If you want to do more analysis, you can pivot, group, or plot the data.

=== DATA FRACTION: 0.03125 (310 rows) ===
Training model: BERT Base (cased)

/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-cased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/usr/local/lib/python3.11/dist-packages/transformers/training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

Full Classification Report:
                precision    recall  f1-score   support

 armed_assault       0.00      0.00      0.00         7
        arrest       0.00      0.00      0.00         8
       bombing       0.00      0.00      0.00         3
infrastructure       0.00      0.00      0.00         5
     surrender       0.00      0.00      0.00         4
       seizure       0.00      0.00      0.00         4
     abduction       0.00      0.00      0.00         1

     micro avg       0.00      0.00      0.00        32
     macro avg       0.00      0.00      0.00        32
  weighted avg       0.00      0.00      0.00        32
   samples avg       0.00      0.00      0.00        32


Full Classification Report:
                precision    recall  f1-score   support

 armed_assault       0.00      0.00      0.00         7
        arrest       0.00      0.00      0.00         8
       bombing       0.00      0.00      0.00         3
infrastructure       0.00      0.00      0.00         5
     surrender       0.00      0.00      0.00         4
       seizure       0.00      0.00      0.00         4
     abduction       0.00      0.00      0.00         1

     micro avg       0.00      0.00      0.00        32
     macro avg       0.00      0.00      0.00        32
  weighted avg       0.00      0.00      0.00        32
   samples avg       0.00      0.00      0.00        32

Full Classification Report:
                precision    recall  f1-score   support

 armed_assault       0.00      0.00      0.00         1
        arrest       0.00      0.00      0.00         0
       bombing       0.00      0.00      0.00         1
infrastructure       0.00      0.00      0.00         1
     surrender       0.00      0.00      0.00         1
       seizure       0.00      0.00      0.00         0
     abduction       0.00      0.00      0.00         1

     micro avg       0.00      0.00      0.00         5
     macro avg       0.00      0.00      0.00         5
  weighted avg       0.00      0.00      0.00         5
   samples avg       0.00      0.00      0.00         5

Test Set Results: {'eval_loss': 0.5474851131439209, 'eval_hamming_loss': 0.17857142857142858, 'eval_subset_accuracy': 0.0, 'eval_arrest': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 1.0}, 'eval_bombing': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 0.0}, 'eval_infrastructure': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 1.0}, 'eval_surrender': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 1.0}, 'eval_seizure': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 1.0}, 'eval_abduction': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 0.0}, 'eval_incident_summary': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 1.0}, 'eval_micro avg': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 5.0}, 'eval_macro avg': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 5.0}, 'eval_weighted avg': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 5.0}, 'eval_samples avg': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 5.0}, 'eval_runtime': 0.1913, 'eval_samples_per_second': 20.915, 'eval_steps_per_second': 5.229, 'epoch': 2.0}
Training model: ConfliBERT-scr-cased

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at snowood1/ConfliBERT-scr-cased and are newly initialized: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight', 'classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/usr/local/lib/python3.11/dist-packages/transformers/training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

Full Classification Report:
                precision    recall  f1-score   support

 armed_assault       0.00      0.00      0.00         7
        arrest       0.00      0.00      0.00         8
       bombing       0.00      0.00      0.00         3
infrastructure       0.00      0.00      0.00         5
     surrender       0.00      0.00      0.00         4
       seizure       0.00      0.00      0.00         4
     abduction       0.00      0.00      0.00         1

     micro avg       0.00      0.00      0.00        32
     macro avg       0.00      0.00      0.00        32
  weighted avg       0.00      0.00      0.00        32
   samples avg       0.00      0.00      0.00        32


Full Classification Report:
                precision    recall  f1-score   support

 armed_assault       0.00      0.00      0.00         7
        arrest       0.00      0.00      0.00         8
       bombing       0.00      0.00      0.00         3
infrastructure       0.00      0.00      0.00         5
     surrender       0.00      0.00      0.00         4
       seizure       0.00      0.00      0.00         4
     abduction       0.00      0.00      0.00         1

     micro avg       0.00      0.00      0.00        32
     macro avg       0.00      0.00      0.00        32
  weighted avg       0.00      0.00      0.00        32
   samples avg       0.00      0.00      0.00        32

Full Classification Report:
                precision    recall  f1-score   support

 armed_assault       0.00      0.00      0.00         1
        arrest       0.00      0.00      0.00         0
       bombing       0.00      0.00      0.00         1
infrastructure       0.00      0.00      0.00         1
     surrender       0.00      0.00      0.00         1
       seizure       0.00      0.00      0.00         0
     abduction       0.00      0.00      0.00         1

     micro avg       0.00      0.00      0.00         5
     macro avg       0.00      0.00      0.00         5
  weighted avg       0.00      0.00      0.00         5
   samples avg       0.00      0.00      0.00         5

Test Set Results: {'eval_loss': 0.5117756724357605, 'eval_hamming_loss': 0.17857142857142858, 'eval_subset_accuracy': 0.0, 'eval_arrest': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 1.0}, 'eval_bombing': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 0.0}, 'eval_infrastructure': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 1.0}, 'eval_surrender': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 1.0}, 'eval_seizure': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 1.0}, 'eval_abduction': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 0.0}, 'eval_incident_summary': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 1.0}, 'eval_micro avg': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 5.0}, 'eval_macro avg': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 5.0}, 'eval_weighted avg': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 5.0}, 'eval_samples avg': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 5.0}, 'eval_runtime': 0.1779, 'eval_samples_per_second': 22.483, 'eval_steps_per_second': 5.621, 'epoch': 2.0}
Training model: RoBERTa Base

tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/481 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/499M [00:00<?, ?B/s]

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at FacebookAI/roberta-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/usr/local/lib/python3.11/dist-packages/transformers/training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

Full Classification Report:
                precision    recall  f1-score   support

 armed_assault       0.00      0.00      0.00         7
        arrest       0.00      0.00      0.00         8
       bombing       0.00      0.00      0.00         3
infrastructure       0.00      0.00      0.00         5
     surrender       0.00      0.00      0.00         4
       seizure       0.00      0.00      0.00         4
     abduction       0.00      0.00      0.00         1

     micro avg       0.00      0.00      0.00        32
     macro avg       0.00      0.00      0.00        32
  weighted avg       0.00      0.00      0.00        32
   samples avg       0.00      0.00      0.00        32


Full Classification Report:
                precision    recall  f1-score   support

 armed_assault       0.00      0.00      0.00         7
        arrest       0.00      0.00      0.00         8
       bombing       0.00      0.00      0.00         3
infrastructure       0.00      0.00      0.00         5
     surrender       0.00      0.00      0.00         4
       seizure       0.00      0.00      0.00         4
     abduction       0.00      0.00      0.00         1

     micro avg       0.00      0.00      0.00        32
     macro avg       0.00      0.00      0.00        32
  weighted avg       0.00      0.00      0.00        32
   samples avg       0.00      0.00      0.00        32

Full Classification Report:
                precision    recall  f1-score   support

 armed_assault       0.00      0.00      0.00         1
        arrest       0.00      0.00      0.00         0
       bombing       0.00      0.00      0.00         1
infrastructure       0.00      0.00      0.00         1
     surrender       0.00      0.00      0.00         1
       seizure       0.00      0.00      0.00         0
     abduction       0.00      0.00      0.00         1

     micro avg       0.00      0.00      0.00         5
     macro avg       0.00      0.00      0.00         5
  weighted avg       0.00      0.00      0.00         5
   samples avg       0.00      0.00      0.00         5

Test Set Results: {'eval_loss': 0.522482693195343, 'eval_hamming_loss': 0.17857142857142858, 'eval_subset_accuracy': 0.0, 'eval_arrest': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 1.0}, 'eval_bombing': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 0.0}, 'eval_infrastructure': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 1.0}, 'eval_surrender': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 1.0}, 'eval_seizure': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 1.0}, 'eval_abduction': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 0.0}, 'eval_incident_summary': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 1.0}, 'eval_micro avg': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 5.0}, 'eval_macro avg': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 5.0}, 'eval_weighted avg': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 5.0}, 'eval_samples avg': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 5.0}, 'eval_runtime': 0.1916, 'eval_samples_per_second': 20.882, 'eval_steps_per_second': 5.221, 'epoch': 2.0}
Training model: DistilBERT (cased)

tokenizer_config.json:   0%|          | 0.00/49.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/465 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/213k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/436k [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/263M [00:00<?, ?B/s]

Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-cased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/usr/local/lib/python3.11/dist-packages/transformers/training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

Full Classification Report:
                precision    recall  f1-score   support

 armed_assault       0.00      0.00      0.00         7
        arrest       0.00      0.00      0.00         8
       bombing       0.00      0.00      0.00         3
infrastructure       0.00      0.00      0.00         5
     surrender       0.00      0.00      0.00         4
       seizure       0.00      0.00      0.00         4
     abduction       0.00      0.00      0.00         1

     micro avg       0.00      0.00      0.00        32
     macro avg       0.00      0.00      0.00        32
  weighted avg       0.00      0.00      0.00        32
   samples avg       0.00      0.00      0.00        32


Full Classification Report:
                precision    recall  f1-score   support

 armed_assault       0.00      0.00      0.00         7
        arrest       0.00      0.00      0.00         8
       bombing       0.00      0.00      0.00         3
infrastructure       0.00      0.00      0.00         5
     surrender       0.00      0.00      0.00         4
       seizure       0.00      0.00      0.00         4
     abduction       0.00      0.00      0.00         1

     micro avg       0.00      0.00      0.00        32
     macro avg       0.00      0.00      0.00        32
  weighted avg       0.00      0.00      0.00        32
   samples avg       0.00      0.00      0.00        32

Full Classification Report:
                precision    recall  f1-score   support

 armed_assault       0.00      0.00      0.00         1
        arrest       0.00      0.00      0.00         0
       bombing       0.00      0.00      0.00         1
infrastructure       0.00      0.00      0.00         1
     surrender       0.00      0.00      0.00         1
       seizure       0.00      0.00      0.00         0
     abduction       0.00      0.00      0.00         1

     micro avg       0.00      0.00      0.00         5
     macro avg       0.00      0.00      0.00         5
  weighted avg       0.00      0.00      0.00         5
   samples avg       0.00      0.00      0.00         5

Test Set Results: {'eval_loss': 0.5680841207504272, 'eval_hamming_loss': 0.17857142857142858, 'eval_subset_accuracy': 0.0, 'eval_arrest': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 1.0}, 'eval_bombing': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 0.0}, 'eval_infrastructure': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 1.0}, 'eval_surrender': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 1.0}, 'eval_seizure': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 1.0}, 'eval_abduction': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 0.0}, 'eval_incident_summary': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 1.0}, 'eval_micro avg': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 5.0}, 'eval_macro avg': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 5.0}, 'eval_weighted avg': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 5.0}, 'eval_samples avg': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 5.0}, 'eval_runtime': 0.111, 'eval_samples_per_second': 36.026, 'eval_steps_per_second': 9.007, 'epoch': 2.0}
Training model: XLNet Base (cased)

config.json:   0%|          | 0.00/760 [00:00<?, ?B/s]

spiece.model:   0%|          | 0.00/798k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.38M [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/467M [00:00<?, ?B/s]

Some weights of XLNetForSequenceClassification were not initialized from the model checkpoint at xlnet-base-cased and are newly initialized: ['logits_proj.bias', 'logits_proj.weight', 'sequence_summary.summary.bias', 'sequence_summary.summary.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/usr/local/lib/python3.11/dist-packages/transformers/training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

model.safetensors:   0%|          | 0.00/467M [00:00<?, ?B/s]

Full Classification Report:
                precision    recall  f1-score   support

 armed_assault       1.00      0.14      0.25         7
        arrest       0.75      0.38      0.50         8
       bombing       0.00      0.00      0.00         3
infrastructure       0.00      0.00      0.00         5
     surrender       0.00      0.00      0.00         4
       seizure       0.00      0.00      0.00         4
     abduction       0.00      0.00      0.00         1

     micro avg       0.80      0.12      0.22        32
     macro avg       0.25      0.07      0.11        32
  weighted avg       0.41      0.12      0.18        32
   samples avg       0.15      0.15      0.15        32


Full Classification Report:
                precision    recall  f1-score   support

 armed_assault       1.00      0.14      0.25         7
        arrest       1.00      0.38      0.55         8
       bombing       0.00      0.00      0.00         3
infrastructure       0.00      0.00      0.00         5
     surrender       0.00      0.00      0.00         4
       seizure       0.00      0.00      0.00         4
     abduction       0.00      0.00      0.00         1

     micro avg       1.00      0.12      0.22        32
     macro avg       0.29      0.07      0.11        32
  weighted avg       0.47      0.12      0.19        32
   samples avg       0.15      0.15      0.15        32

Full Classification Report:
                precision    recall  f1-score   support

 armed_assault       0.00      0.00      0.00         1
        arrest       0.00      0.00      0.00         0
       bombing       0.00      0.00      0.00         1
infrastructure       0.00      0.00      0.00         1
     surrender       0.00      0.00      0.00         1
       seizure       0.00      0.00      0.00         0
     abduction       0.00      0.00      0.00         1

     micro avg       0.00      0.00      0.00         5
     macro avg       0.00      0.00      0.00         5
  weighted avg       0.00      0.00      0.00         5
   samples avg       0.00      0.00      0.00         5

Test Set Results: {'eval_loss': 0.5717599391937256, 'eval_hamming_loss': 0.17857142857142858, 'eval_subset_accuracy': 0.0, 'eval_arrest': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 1.0}, 'eval_bombing': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 0.0}, 'eval_infrastructure': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 1.0}, 'eval_surrender': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 1.0}, 'eval_seizure': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 1.0}, 'eval_abduction': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 0.0}, 'eval_incident_summary': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 1.0}, 'eval_micro avg': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 5.0}, 'eval_macro avg': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 5.0}, 'eval_weighted avg': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 5.0}, 'eval_samples avg': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 5.0}, 'eval_runtime': 0.4387, 'eval_samples_per_second': 9.117, 'eval_steps_per_second': 2.279, 'epoch': 2.0}
Training model: ELECTRA Base

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/666 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/440M [00:00<?, ?B/s]

Some weights of ElectraForSequenceClassification were not initialized from the model checkpoint at google/electra-base-discriminator and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/usr/local/lib/python3.11/dist-packages/transformers/training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

Full Classification Report:
                precision    recall  f1-score   support

 armed_assault       0.00      0.00      0.00         7
        arrest       0.00      0.00      0.00         8
       bombing       0.00      0.00      0.00         3
infrastructure       0.00      0.00      0.00         5
     surrender       0.00      0.00      0.00         4
       seizure       0.00      0.00      0.00         4
     abduction       0.00      0.00      0.00         1

     micro avg       0.00      0.00      0.00        32
     macro avg       0.00      0.00      0.00        32
  weighted avg       0.00      0.00      0.00        32
   samples avg       0.00      0.00      0.00        32


Full Classification Report:
                precision    recall  f1-score   support

 armed_assault       0.00      0.00      0.00         7
        arrest       0.00      0.00      0.00         8
       bombing       0.00      0.00      0.00         3
infrastructure       0.00      0.00      0.00         5
     surrender       0.00      0.00      0.00         4
       seizure       0.00      0.00      0.00         4
     abduction       0.00      0.00      0.00         1

     micro avg       0.00      0.00      0.00        32
     macro avg       0.00      0.00      0.00        32
  weighted avg       0.00      0.00      0.00        32
   samples avg       0.00      0.00      0.00        32

Full Classification Report:
                precision    recall  f1-score   support

 armed_assault       0.00      0.00      0.00         1
        arrest       0.00      0.00      0.00         0
       bombing       0.00      0.00      0.00         1
infrastructure       0.00      0.00      0.00         1
     surrender       0.00      0.00      0.00         1
       seizure       0.00      0.00      0.00         0
     abduction       0.00      0.00      0.00         1

     micro avg       0.00      0.00      0.00         5
     macro avg       0.00      0.00      0.00         5
  weighted avg       0.00      0.00      0.00         5
   samples avg       0.00      0.00      0.00         5

Test Set Results: {'eval_loss': 0.5791929960250854, 'eval_hamming_loss': 0.17857142857142858, 'eval_subset_accuracy': 0.0, 'eval_arrest': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 1.0}, 'eval_bombing': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 0.0}, 'eval_infrastructure': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 1.0}, 'eval_surrender': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 1.0}, 'eval_seizure': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 1.0}, 'eval_abduction': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 0.0}, 'eval_incident_summary': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 1.0}, 'eval_micro avg': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 5.0}, 'eval_macro avg': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 5.0}, 'eval_weighted avg': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 5.0}, 'eval_samples avg': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 5.0}, 'eval_runtime': 0.1955, 'eval_samples_per_second': 20.455, 'eval_steps_per_second': 5.114, 'epoch': 2.0}

=== DATA FRACTION: 0.0625 (620 rows) ===
Training model: BERT Base (cased)

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-cased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/usr/local/lib/python3.11/dist-packages/transformers/training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

Full Classification Report:
                precision    recall  f1-score   support

 armed_assault       0.20      0.08      0.11        13
        arrest       0.00      0.00      0.00        22
       bombing       0.00      0.00      0.00         6
infrastructure       1.00      0.17      0.29         6
     surrender       0.00      0.00      0.00         4
       seizure       0.00      0.00      0.00         8
     abduction       0.00      0.00      0.00         2

     micro avg       0.33      0.03      0.06        61
     macro avg       0.17      0.03      0.06        61
  weighted avg       0.14      0.03      0.05        61
   samples avg       0.03      0.04      0.03        61


Full Classification Report:
                precision    recall  f1-score   support

 armed_assault       0.63      0.92      0.75        13
        arrest       0.95      0.95      0.95        22
       bombing       0.00      0.00      0.00         6
infrastructure       1.00      0.50      0.67         6
     surrender       0.00      0.00      0.00         4
       seizure       0.00      0.00      0.00         8
     abduction       0.00      0.00      0.00         2

     micro avg       0.82      0.59      0.69        61
     macro avg       0.37      0.34      0.34        61
  weighted avg       0.58      0.59      0.57        61
   samples avg       0.63      0.60      0.60        61

Full Classification Report:
                precision    recall  f1-score   support

 armed_assault       0.00      0.00      0.00         2
        arrest       0.00      0.00      0.00         2
       bombing       0.00      0.00      0.00         1
infrastructure       0.00      0.00      0.00         0
     surrender       0.00      0.00      0.00         1
       seizure       0.00      0.00      0.00         3
     abduction       0.00      0.00      0.00         0

     micro avg       0.00      0.00      0.00         9
     macro avg       0.00      0.00      0.00         9
  weighted avg       0.00      0.00      0.00         9
   samples avg       0.00      0.00      0.00         9

Test Set Results: {'eval_loss': 0.4270182251930237, 'eval_hamming_loss': 0.1836734693877551, 'eval_subset_accuracy': 0.0, 'eval_arrest': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 2.0}, 'eval_bombing': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 2.0}, 'eval_infrastructure': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 1.0}, 'eval_surrender': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 0.0}, 'eval_seizure': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 1.0}, 'eval_abduction': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 3.0}, 'eval_incident_summary': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 0.0}, 'eval_micro avg': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 9.0}, 'eval_macro avg': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 9.0}, 'eval_weighted avg': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 9.0}, 'eval_samples avg': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 9.0}, 'eval_runtime': 0.2698, 'eval_samples_per_second': 25.946, 'eval_steps_per_second': 3.707, 'epoch': 2.0}
Training model: ConfliBERT-scr-cased

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at snowood1/ConfliBERT-scr-cased and are newly initialized: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight', 'classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/usr/local/lib/python3.11/dist-packages/transformers/training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

Full Classification Report:
                precision    recall  f1-score   support

 armed_assault       0.67      0.31      0.42        13
        arrest       0.00      0.00      0.00        22
       bombing       0.00      0.00      0.00         6
infrastructure       0.00      0.00      0.00         6
     surrender       0.00      0.00      0.00         4
       seizure       0.00      0.00      0.00         8
     abduction       0.00      0.00      0.00         2

     micro avg       0.67      0.07      0.12        61
     macro avg       0.10      0.04      0.06        61
  weighted avg       0.14      0.07      0.09        61
   samples avg       0.07      0.07      0.07        61


Full Classification Report:
                precision    recall  f1-score   support

 armed_assault       0.81      1.00      0.90        13
        arrest       1.00      0.86      0.93        22
       bombing       0.00      0.00      0.00         6
infrastructure       0.00      0.00      0.00         6
     surrender       0.00      0.00      0.00         4
       seizure       0.00      0.00      0.00         8
     abduction       0.00      0.00      0.00         2

     micro avg       0.91      0.52      0.67        61
     macro avg       0.26      0.27      0.26        61
  weighted avg       0.53      0.52      0.53        61
   samples avg       0.58      0.53      0.55        61

Full Classification Report:
                precision    recall  f1-score   support

 armed_assault       1.00      1.00      1.00         2
        arrest       0.00      0.00      0.00         2
       bombing       0.00      0.00      0.00         1
infrastructure       0.00      0.00      0.00         0
     surrender       0.00      0.00      0.00         1
       seizure       0.00      0.00      0.00         3
     abduction       0.00      0.00      0.00         0

     micro avg       1.00      0.22      0.36         9
     macro avg       0.14      0.14      0.14         9
  weighted avg       0.22      0.22      0.22         9
   samples avg       0.29      0.29      0.29         9

Test Set Results: {'eval_loss': 0.38561052083969116, 'eval_hamming_loss': 0.14285714285714285, 'eval_subset_accuracy': 0.2857142857142857, 'eval_arrest': {'precision': 1.0, 'recall': 1.0, 'f1-score': 1.0, 'support': 2.0}, 'eval_bombing': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 2.0}, 'eval_infrastructure': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 1.0}, 'eval_surrender': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 0.0}, 'eval_seizure': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 1.0}, 'eval_abduction': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 3.0}, 'eval_incident_summary': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 0.0}, 'eval_micro avg': {'precision': 1.0, 'recall': 0.2222222222222222, 'f1-score': 0.36363636363636365, 'support': 9.0}, 'eval_macro avg': {'precision': 0.14285714285714285, 'recall': 0.14285714285714285, 'f1-score': 0.14285714285714285, 'support': 9.0}, 'eval_weighted avg': {'precision': 0.2222222222222222, 'recall': 0.2222222222222222, 'f1-score': 0.2222222222222222, 'support': 9.0}, 'eval_samples avg': {'precision': 0.2857142857142857, 'recall': 0.2857142857142857, 'f1-score': 0.2857142857142857, 'support': 9.0}, 'eval_runtime': 0.2909, 'eval_samples_per_second': 24.063, 'eval_steps_per_second': 3.438, 'epoch': 2.0}
Training model: RoBERTa Base

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at FacebookAI/roberta-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/usr/local/lib/python3.11/dist-packages/transformers/training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

Full Classification Report:
                precision    recall  f1-score   support

 armed_assault       0.00      0.00      0.00        13
        arrest       0.00      0.00      0.00        22
       bombing       0.00      0.00      0.00         6
infrastructure       0.00      0.00      0.00         6
     surrender       0.00      0.00      0.00         4
       seizure       0.00      0.00      0.00         8
     abduction       0.00      0.00      0.00         2

     micro avg       0.00      0.00      0.00        61
     macro avg       0.00      0.00      0.00        61
  weighted avg       0.00      0.00      0.00        61
   samples avg       0.00      0.00      0.00        61


Full Classification Report:
                precision    recall  f1-score   support

 armed_assault       0.59      1.00      0.74        13
        arrest       0.92      1.00      0.96        22
       bombing       0.00      0.00      0.00         6
infrastructure       0.00      0.00      0.00         6
     surrender       0.00      0.00      0.00         4
       seizure       0.00      0.00      0.00         8
     abduction       0.00      0.00      0.00         2

     micro avg       0.76      0.57      0.65        61
     macro avg       0.22      0.29      0.24        61
  weighted avg       0.46      0.57      0.50        61
   samples avg       0.64      0.58      0.60        61

Full Classification Report:
                precision    recall  f1-score   support

 armed_assault       0.00      0.00      0.00         2
        arrest       0.00      0.00      0.00         2
       bombing       0.00      0.00      0.00         1
infrastructure       0.00      0.00      0.00         0
     surrender       0.00      0.00      0.00         1
       seizure       0.00      0.00      0.00         3
     abduction       0.00      0.00      0.00         0

     micro avg       0.00      0.00      0.00         9
     macro avg       0.00      0.00      0.00         9
  weighted avg       0.00      0.00      0.00         9
   samples avg       0.00      0.00      0.00         9

Test Set Results: {'eval_loss': 0.4182746708393097, 'eval_hamming_loss': 0.1836734693877551, 'eval_subset_accuracy': 0.0, 'eval_arrest': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 2.0}, 'eval_bombing': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 2.0}, 'eval_infrastructure': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 1.0}, 'eval_surrender': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 0.0}, 'eval_seizure': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 1.0}, 'eval_abduction': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 3.0}, 'eval_incident_summary': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 0.0}, 'eval_micro avg': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 9.0}, 'eval_macro avg': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 9.0}, 'eval_weighted avg': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 9.0}, 'eval_samples avg': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 9.0}, 'eval_runtime': 0.2774, 'eval_samples_per_second': 25.238, 'eval_steps_per_second': 3.605, 'epoch': 2.0}
Training model: DistilBERT (cased)

Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-cased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/usr/local/lib/python3.11/dist-packages/transformers/training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

Full Classification Report:
                precision    recall  f1-score   support

 armed_assault       0.00      0.00      0.00        13
        arrest       0.00      0.00      0.00        22
       bombing       0.00      0.00      0.00         6
infrastructure       0.00      0.00      0.00         6
     surrender       0.00      0.00      0.00         4
       seizure       0.00      0.00      0.00         8
     abduction       0.00      0.00      0.00         2

     micro avg       0.00      0.00      0.00        61
     macro avg       0.00      0.00      0.00        61
  weighted avg       0.00      0.00      0.00        61
   samples avg       0.00      0.00      0.00        61


Full Classification Report:
                precision    recall  f1-score   support

 armed_assault       0.00      0.00      0.00        13
        arrest       0.00      0.00      0.00        22
       bombing       0.00      0.00      0.00         6
infrastructure       0.00      0.00      0.00         6
     surrender       0.00      0.00      0.00         4
       seizure       0.00      0.00      0.00         8
     abduction       0.00      0.00      0.00         2

     micro avg       0.00      0.00      0.00        61
     macro avg       0.00      0.00      0.00        61
  weighted avg       0.00      0.00      0.00        61
   samples avg       0.00      0.00      0.00        61

Full Classification Report:
                precision    recall  f1-score   support

 armed_assault       0.00      0.00      0.00         2
        arrest       0.00      0.00      0.00         2
       bombing       0.00      0.00      0.00         1
infrastructure       0.00      0.00      0.00         0
     surrender       0.00      0.00      0.00         1
       seizure       0.00      0.00      0.00         3
     abduction       0.00      0.00      0.00         0

     micro avg       0.00      0.00      0.00         9
     macro avg       0.00      0.00      0.00         9
  weighted avg       0.00      0.00      0.00         9
   samples avg       0.00      0.00      0.00         9

Test Set Results: {'eval_loss': 0.45348092913627625, 'eval_hamming_loss': 0.1836734693877551, 'eval_subset_accuracy': 0.0, 'eval_arrest': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 2.0}, 'eval_bombing': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 2.0}, 'eval_infrastructure': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 1.0}, 'eval_surrender': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 0.0}, 'eval_seizure': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 1.0}, 'eval_abduction': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 3.0}, 'eval_incident_summary': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 0.0}, 'eval_micro avg': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 9.0}, 'eval_macro avg': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 9.0}, 'eval_weighted avg': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 9.0}, 'eval_samples avg': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 9.0}, 'eval_runtime': 0.1791, 'eval_samples_per_second': 39.082, 'eval_steps_per_second': 5.583, 'epoch': 2.0}
Training model: XLNet Base (cased)

Some weights of XLNetForSequenceClassification were not initialized from the model checkpoint at xlnet-base-cased and are newly initialized: ['logits_proj.bias', 'logits_proj.weight', 'sequence_summary.summary.bias', 'sequence_summary.summary.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/usr/local/lib/python3.11/dist-packages/transformers/training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

Full Classification Report:
                precision    recall  f1-score   support

 armed_assault       0.60      0.23      0.33        13
        arrest       0.00      0.00      0.00        22
       bombing       0.00      0.00      0.00         6
infrastructure       0.00      0.00      0.00         6
     surrender       0.00      0.00      0.00         4
       seizure       0.00      0.00      0.00         8
     abduction       0.00      0.00      0.00         2

     micro avg       0.60      0.05      0.09        61
     macro avg       0.09      0.03      0.05        61
  weighted avg       0.13      0.05      0.07        61
   samples avg       0.05      0.05      0.05        61


Full Classification Report:
                precision    recall  f1-score   support

 armed_assault       0.73      0.85      0.79        13
        arrest       1.00      0.95      0.98        22
       bombing       0.00      0.00      0.00         6
infrastructure       0.00      0.00      0.00         6
     surrender       0.00      0.00      0.00         4
       seizure       1.00      0.25      0.40         8
     abduction       0.00      0.00      0.00         2

     micro avg       0.89      0.56      0.69        61
     macro avg       0.39      0.29      0.31        61
  weighted avg       0.65      0.56      0.57        61
   samples avg       0.58      0.55      0.56        61

Full Classification Report:
                precision    recall  f1-score   support

 armed_assault       1.00      0.50      0.67         2
        arrest       0.00      0.00      0.00         2
       bombing       0.00      0.00      0.00         1
infrastructure       0.00      0.00      0.00         0
     surrender       0.00      0.00      0.00         1
       seizure       0.00      0.00      0.00         3
     abduction       0.00      0.00      0.00         0

     micro avg       1.00      0.11      0.20         9
     macro avg       0.14      0.07      0.10         9
  weighted avg       0.22      0.11      0.15         9
   samples avg       0.14      0.14      0.14         9

Test Set Results: {'eval_loss': 0.355651319026947, 'eval_hamming_loss': 0.16326530612244897, 'eval_subset_accuracy': 0.14285714285714285, 'eval_arrest': {'precision': 1.0, 'recall': 0.5, 'f1-score': 0.6666666666666666, 'support': 2.0}, 'eval_bombing': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 2.0}, 'eval_infrastructure': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 1.0}, 'eval_surrender': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 0.0}, 'eval_seizure': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 1.0}, 'eval_abduction': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 3.0}, 'eval_incident_summary': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 0.0}, 'eval_micro avg': {'precision': 1.0, 'recall': 0.1111111111111111, 'f1-score': 0.2, 'support': 9.0}, 'eval_macro avg': {'precision': 0.14285714285714285, 'recall': 0.07142857142857142, 'f1-score': 0.09523809523809523, 'support': 9.0}, 'eval_weighted avg': {'precision': 0.2222222222222222, 'recall': 0.1111111111111111, 'f1-score': 0.14814814814814814, 'support': 9.0}, 'eval_samples avg': {'precision': 0.14285714285714285, 'recall': 0.14285714285714285, 'f1-score': 0.14285714285714285, 'support': 9.0}, 'eval_runtime': 0.7286, 'eval_samples_per_second': 9.608, 'eval_steps_per_second': 1.373, 'epoch': 2.0}
Training model: ELECTRA Base

Some weights of ElectraForSequenceClassification were not initialized from the model checkpoint at google/electra-base-discriminator and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/usr/local/lib/python3.11/dist-packages/transformers/training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

Full Classification Report:
                precision    recall  f1-score   support

 armed_assault       0.00      0.00      0.00        13
        arrest       0.00      0.00      0.00        22
       bombing       0.00      0.00      0.00         6
infrastructure       0.00      0.00      0.00         6
     surrender       0.00      0.00      0.00         4
       seizure       0.00      0.00      0.00         8
     abduction       0.00      0.00      0.00         2

     micro avg       0.00      0.00      0.00        61
     macro avg       0.00      0.00      0.00        61
  weighted avg       0.00      0.00      0.00        61
   samples avg       0.00      0.00      0.00        61


Full Classification Report:
                precision    recall  f1-score   support

 armed_assault       0.00      0.00      0.00        13
        arrest       0.00      0.00      0.00        22
       bombing       0.00      0.00      0.00         6
infrastructure       0.00      0.00      0.00         6
     surrender       0.00      0.00      0.00         4
       seizure       0.00      0.00      0.00         8
     abduction       0.00      0.00      0.00         2

     micro avg       0.00      0.00      0.00        61
     macro avg       0.00      0.00      0.00        61
  weighted avg       0.00      0.00      0.00        61
   samples avg       0.00      0.00      0.00        61

Full Classification Report:
                precision    recall  f1-score   support

 armed_assault       0.00      0.00      0.00         2
        arrest       0.00      0.00      0.00         2
       bombing       0.00      0.00      0.00         1
infrastructure       0.00      0.00      0.00         0
     surrender       0.00      0.00      0.00         1
       seizure       0.00      0.00      0.00         3
     abduction       0.00      0.00      0.00         0

     micro avg       0.00      0.00      0.00         9
     macro avg       0.00      0.00      0.00         9
  weighted avg       0.00      0.00      0.00         9
   samples avg       0.00      0.00      0.00         9

Test Set Results: {'eval_loss': 0.4847027659416199, 'eval_hamming_loss': 0.1836734693877551, 'eval_subset_accuracy': 0.0, 'eval_arrest': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 2.0}, 'eval_bombing': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 2.0}, 'eval_infrastructure': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 1.0}, 'eval_surrender': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 0.0}, 'eval_seizure': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 1.0}, 'eval_abduction': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 3.0}, 'eval_incident_summary': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 0.0}, 'eval_micro avg': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 9.0}, 'eval_macro avg': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 9.0}, 'eval_weighted avg': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 9.0}, 'eval_samples avg': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 9.0}, 'eval_runtime': 0.2962, 'eval_samples_per_second': 23.632, 'eval_steps_per_second': 3.376, 'epoch': 2.0}

=== DATA FRACTION: 0.125 (1240 rows) ===
Training model: BERT Base (cased)

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-cased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/usr/local/lib/python3.11/dist-packages/transformers/training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

Full Classification Report:
                precision    recall  f1-score   support

 armed_assault       0.95      0.93      0.94        41
        arrest       1.00      1.00      1.00        32
       bombing       0.00      0.00      0.00        10
infrastructure       1.00      0.36      0.53        14
     surrender       0.00      0.00      0.00         6
       seizure       0.00      0.00      0.00        21
     abduction       0.00      0.00      0.00        10

     micro avg       0.97      0.56      0.71       134
     macro avg       0.42      0.33      0.35       134
  weighted avg       0.63      0.56      0.58       134
   samples avg       0.68      0.59      0.62       134


Full Classification Report:
                precision    recall  f1-score   support

 armed_assault       0.97      0.93      0.95        41
        arrest       1.00      1.00      1.00        32
       bombing       0.00      0.00      0.00        10
infrastructure       0.88      0.50      0.64        14
     surrender       1.00      1.00      1.00         6
       seizure       1.00      0.52      0.69        21
     abduction       0.00      0.00      0.00        10

     micro avg       0.98      0.70      0.82       134
     macro avg       0.69      0.56      0.61       134
  weighted avg       0.83      0.70      0.75       134
   samples avg       0.79      0.73      0.75       134

Full Classification Report:
                precision    recall  f1-score   support

 armed_assault       1.00      1.00      1.00         5
        arrest       1.00      1.00      1.00         3
       bombing       0.00      0.00      0.00         2
infrastructure       1.00      0.33      0.50         3
     surrender       0.00      0.00      0.00         1
       seizure       0.00      0.00      0.00         2
     abduction       0.00      0.00      0.00         1

     micro avg       1.00      0.53      0.69        17
     macro avg       0.43      0.33      0.36        17
  weighted avg       0.65      0.53      0.56        17
   samples avg       0.69      0.56      0.60        17

Test Set Results: {'eval_loss': 0.32205599546432495, 'eval_hamming_loss': 0.08791208791208792, 'eval_subset_accuracy': 0.46153846153846156, 'eval_arrest': {'precision': 1.0, 'recall': 1.0, 'f1-score': 1.0, 'support': 5.0}, 'eval_bombing': {'precision': 1.0, 'recall': 1.0, 'f1-score': 1.0, 'support': 3.0}, 'eval_infrastructure': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 2.0}, 'eval_surrender': {'precision': 1.0, 'recall': 0.3333333333333333, 'f1-score': 0.5, 'support': 3.0}, 'eval_seizure': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 1.0}, 'eval_abduction': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 2.0}, 'eval_incident_summary': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 1.0}, 'eval_micro avg': {'precision': 1.0, 'recall': 0.5294117647058824, 'f1-score': 0.6923076923076923, 'support': 17.0}, 'eval_macro avg': {'precision': 0.42857142857142855, 'recall': 0.33333333333333337, 'f1-score': 0.35714285714285715, 'support': 17.0}, 'eval_weighted avg': {'precision': 0.6470588235294118, 'recall': 0.5294117647058824, 'f1-score': 0.5588235294117647, 'support': 17.0}, 'eval_samples avg': {'precision': 0.6923076923076923, 'recall': 0.5641025641025641, 'f1-score': 0.6025641025641025, 'support': 17.0}, 'eval_runtime': 0.4432, 'eval_samples_per_second': 29.33, 'eval_steps_per_second': 2.256, 'epoch': 2.0}
Training model: ConfliBERT-scr-cased

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at snowood1/ConfliBERT-scr-cased and are newly initialized: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight', 'classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/usr/local/lib/python3.11/dist-packages/transformers/training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

Full Classification Report:
                precision    recall  f1-score   support

 armed_assault       0.95      0.93      0.94        41
        arrest       0.97      1.00      0.98        32
       bombing       0.00      0.00      0.00        10
infrastructure       0.00      0.00      0.00        14
     surrender       0.00      0.00      0.00         6
       seizure       0.00      0.00      0.00        21
     abduction       0.00      0.00      0.00        10

     micro avg       0.96      0.52      0.68       134
     macro avg       0.27      0.28      0.27       134
  weighted avg       0.52      0.52      0.52       134
   samples avg       0.63      0.54      0.57       134


Full Classification Report:
                precision    recall  f1-score   support

 armed_assault       1.00      0.93      0.96        41
        arrest       0.97      1.00      0.98        32
       bombing       0.67      0.20      0.31        10
infrastructure       0.88      0.50      0.64        14
     surrender       1.00      1.00      1.00         6
       seizure       1.00      0.62      0.76        21
     abduction       0.00      0.00      0.00        10

     micro avg       0.97      0.73      0.83       134
     macro avg       0.79      0.61      0.67       134
  weighted avg       0.88      0.73      0.78       134
   samples avg       0.82      0.76      0.78       134

Full Classification Report:
                precision    recall  f1-score   support

 armed_assault       1.00      0.60      0.75         5
        arrest       1.00      1.00      1.00         3
       bombing       0.00      0.00      0.00         2
infrastructure       0.00      0.00      0.00         3
     surrender       0.00      0.00      0.00         1
       seizure       0.00      0.00      0.00         2
     abduction       0.00      0.00      0.00         1

     micro avg       1.00      0.35      0.52        17
     macro avg       0.29      0.23      0.25        17
  weighted avg       0.47      0.35      0.40        17
   samples avg       0.46      0.37      0.40        17

Test Set Results: {'eval_loss': 0.2940659523010254, 'eval_hamming_loss': 0.12087912087912088, 'eval_subset_accuracy': 0.3076923076923077, 'eval_arrest': {'precision': 1.0, 'recall': 0.6, 'f1-score': 0.75, 'support': 5.0}, 'eval_bombing': {'precision': 1.0, 'recall': 1.0, 'f1-score': 1.0, 'support': 3.0}, 'eval_infrastructure': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 2.0}, 'eval_surrender': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 3.0}, 'eval_seizure': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 1.0}, 'eval_abduction': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 2.0}, 'eval_incident_summary': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 1.0}, 'eval_micro avg': {'precision': 1.0, 'recall': 0.35294117647058826, 'f1-score': 0.5217391304347826, 'support': 17.0}, 'eval_macro avg': {'precision': 0.2857142857142857, 'recall': 0.2285714285714286, 'f1-score': 0.25, 'support': 17.0}, 'eval_weighted avg': {'precision': 0.47058823529411764, 'recall': 0.35294117647058826, 'f1-score': 0.39705882352941174, 'support': 17.0}, 'eval_samples avg': {'precision': 0.46153846153846156, 'recall': 0.37179487179487175, 'f1-score': 0.3974358974358974, 'support': 17.0}, 'eval_runtime': 0.4231, 'eval_samples_per_second': 30.729, 'eval_steps_per_second': 2.364, 'epoch': 2.0}
Training model: RoBERTa Base

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at FacebookAI/roberta-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/usr/local/lib/python3.11/dist-packages/transformers/training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

Full Classification Report:
                precision    recall  f1-score   support

 armed_assault       0.88      0.88      0.88        41
        arrest       0.97      1.00      0.98        32
       bombing       0.00      0.00      0.00        10
infrastructure       0.00      0.00      0.00        14
     surrender       0.00      0.00      0.00         6
       seizure       0.81      0.62      0.70        21
     abduction       0.00      0.00      0.00        10

     micro avg       0.90      0.60      0.72       134
     macro avg       0.38      0.36      0.37       134
  weighted avg       0.63      0.60      0.61       134
   samples avg       0.67      0.61      0.63       134


Full Classification Report:
                precision    recall  f1-score   support

 armed_assault       0.93      0.90      0.91        41
        arrest       0.97      1.00      0.98        32
       bombing       0.00      0.00      0.00        10
infrastructure       1.00      0.50      0.67        14
     surrender       1.00      1.00      1.00         6
       seizure       0.85      0.81      0.83        21
     abduction       0.00      0.00      0.00        10

     micro avg       0.93      0.74      0.82       134
     macro avg       0.68      0.60      0.63       134
  weighted avg       0.80      0.74      0.76       134
   samples avg       0.81      0.76      0.77       134

Full Classification Report:
                precision    recall  f1-score   support

 armed_assault       1.00      0.80      0.89         5
        arrest       1.00      1.00      1.00         3
       bombing       0.00      0.00      0.00         2
infrastructure       0.00      0.00      0.00         3
     surrender       0.00      0.00      0.00         1
       seizure       1.00      0.50      0.67         2
     abduction       0.00      0.00      0.00         1

     micro avg       1.00      0.47      0.64        17
     macro avg       0.43      0.33      0.37        17
  weighted avg       0.59      0.47      0.52        17
   samples avg       0.62      0.49      0.53        17

Test Set Results: {'eval_loss': 0.2812030613422394, 'eval_hamming_loss': 0.0989010989010989, 'eval_subset_accuracy': 0.38461538461538464, 'eval_arrest': {'precision': 1.0, 'recall': 0.8, 'f1-score': 0.8888888888888888, 'support': 5.0}, 'eval_bombing': {'precision': 1.0, 'recall': 1.0, 'f1-score': 1.0, 'support': 3.0}, 'eval_infrastructure': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 2.0}, 'eval_surrender': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 3.0}, 'eval_seizure': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 1.0}, 'eval_abduction': {'precision': 1.0, 'recall': 0.5, 'f1-score': 0.6666666666666666, 'support': 2.0}, 'eval_incident_summary': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 1.0}, 'eval_micro avg': {'precision': 1.0, 'recall': 0.47058823529411764, 'f1-score': 0.64, 'support': 17.0}, 'eval_macro avg': {'precision': 0.42857142857142855, 'recall': 0.32857142857142857, 'f1-score': 0.36507936507936506, 'support': 17.0}, 'eval_weighted avg': {'precision': 0.5882352941176471, 'recall': 0.47058823529411764, 'f1-score': 0.5163398692810458, 'support': 17.0}, 'eval_samples avg': {'precision': 0.6153846153846154, 'recall': 0.4871794871794872, 'f1-score': 0.5256410256410257, 'support': 17.0}, 'eval_runtime': 0.4095, 'eval_samples_per_second': 31.748, 'eval_steps_per_second': 2.442, 'epoch': 2.0}
Training model: DistilBERT (cased)

Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-cased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/usr/local/lib/python3.11/dist-packages/transformers/training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

Full Classification Report:
                precision    recall  f1-score   support

 armed_assault       1.00      0.17      0.29        41
        arrest       1.00      0.94      0.97        32
       bombing       0.00      0.00      0.00        10
infrastructure       0.00      0.00      0.00        14
     surrender       0.00      0.00      0.00         6
       seizure       0.00      0.00      0.00        21
     abduction       0.00      0.00      0.00        10

     micro avg       1.00      0.28      0.43       134
     macro avg       0.29      0.16      0.18       134
  weighted avg       0.54      0.28      0.32       134
   samples avg       0.33      0.29      0.31       134


Full Classification Report:
                precision    recall  f1-score   support

 armed_assault       0.78      0.93      0.84        41
        arrest       1.00      1.00      1.00        32
       bombing       0.00      0.00      0.00        10
infrastructure       0.00      0.00      0.00        14
     surrender       0.00      0.00      0.00         6
       seizure       0.00      0.00      0.00        21
     abduction       0.00      0.00      0.00        10

     micro avg       0.86      0.52      0.65       134
     macro avg       0.25      0.28      0.26       134
  weighted avg       0.48      0.52      0.50       134
   samples avg       0.63      0.54      0.57       134

Full Classification Report:
                precision    recall  f1-score   support

 armed_assault       0.00      0.00      0.00         5
        arrest       1.00      1.00      1.00         3
       bombing       0.00      0.00      0.00         2
infrastructure       0.00      0.00      0.00         3
     surrender       0.00      0.00      0.00         1
       seizure       0.00      0.00      0.00         2
     abduction       0.00      0.00      0.00         1

     micro avg       1.00      0.18      0.30        17
     macro avg       0.14      0.14      0.14        17
  weighted avg       0.18      0.18      0.18        17
   samples avg       0.23      0.19      0.21        17

Test Set Results: {'eval_loss': 0.3876505494117737, 'eval_hamming_loss': 0.15384615384615385, 'eval_subset_accuracy': 0.15384615384615385, 'eval_arrest': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 5.0}, 'eval_bombing': {'precision': 1.0, 'recall': 1.0, 'f1-score': 1.0, 'support': 3.0}, 'eval_infrastructure': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 2.0}, 'eval_surrender': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 3.0}, 'eval_seizure': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 1.0}, 'eval_abduction': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 2.0}, 'eval_incident_summary': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 1.0}, 'eval_micro avg': {'precision': 1.0, 'recall': 0.17647058823529413, 'f1-score': 0.3, 'support': 17.0}, 'eval_macro avg': {'precision': 0.14285714285714285, 'recall': 0.14285714285714285, 'f1-score': 0.14285714285714285, 'support': 17.0}, 'eval_weighted avg': {'precision': 0.17647058823529413, 'recall': 0.17647058823529413, 'f1-score': 0.17647058823529413, 'support': 17.0}, 'eval_samples avg': {'precision': 0.23076923076923078, 'recall': 0.19230769230769232, 'f1-score': 0.20512820512820512, 'support': 17.0}, 'eval_runtime': 0.2898, 'eval_samples_per_second': 44.855, 'eval_steps_per_second': 3.45, 'epoch': 2.0}
Training model: XLNet Base (cased)

Some weights of XLNetForSequenceClassification were not initialized from the model checkpoint at xlnet-base-cased and are newly initialized: ['logits_proj.bias', 'logits_proj.weight', 'sequence_summary.summary.bias', 'sequence_summary.summary.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/usr/local/lib/python3.11/dist-packages/transformers/training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

Full Classification Report:
                precision    recall  f1-score   support

 armed_assault       1.00      0.93      0.96        41
        arrest       1.00      1.00      1.00        32
       bombing       0.83      0.50      0.62        10
infrastructure       1.00      0.29      0.44        14
     surrender       1.00      1.00      1.00         6
       seizure       0.77      0.81      0.79        21
     abduction       0.00      0.00      0.00        10

     micro avg       0.94      0.76      0.84       134
     macro avg       0.80      0.65      0.69       134
  weighted avg       0.88      0.76      0.79       134
   samples avg       0.82      0.79      0.79       134


Full Classification Report:
                precision    recall  f1-score   support

 armed_assault       1.00      0.93      0.96        41
        arrest       1.00      1.00      1.00        32
       bombing       0.82      0.90      0.86        10
infrastructure       1.00      0.64      0.78        14
     surrender       1.00      1.00      1.00         6
       seizure       0.90      0.86      0.88        21
     abduction       1.00      0.10      0.18        10

     micro avg       0.97      0.84      0.90       134
     macro avg       0.96      0.78      0.81       134
  weighted avg       0.97      0.84      0.87       134
   samples avg       0.91      0.88      0.89       134

Full Classification Report:
                precision    recall  f1-score   support

 armed_assault       1.00      0.40      0.57         5
        arrest       1.00      1.00      1.00         3
       bombing       0.00      0.00      0.00         2
infrastructure       1.00      0.67      0.80         3
     surrender       1.00      1.00      1.00         1
       seizure       1.00      0.50      0.67         2
     abduction       0.00      0.00      0.00         1

     micro avg       1.00      0.53      0.69        17
     macro avg       0.71      0.51      0.58        17
  weighted avg       0.82      0.53      0.62        17
   samples avg       0.69      0.62      0.64        17

Test Set Results: {'eval_loss': 0.21726201474666595, 'eval_hamming_loss': 0.08791208791208792, 'eval_subset_accuracy': 0.5384615384615384, 'eval_arrest': {'precision': 1.0, 'recall': 0.4, 'f1-score': 0.5714285714285714, 'support': 5.0}, 'eval_bombing': {'precision': 1.0, 'recall': 1.0, 'f1-score': 1.0, 'support': 3.0}, 'eval_infrastructure': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 2.0}, 'eval_surrender': {'precision': 1.0, 'recall': 0.6666666666666666, 'f1-score': 0.8, 'support': 3.0}, 'eval_seizure': {'precision': 1.0, 'recall': 1.0, 'f1-score': 1.0, 'support': 1.0}, 'eval_abduction': {'precision': 1.0, 'recall': 0.5, 'f1-score': 0.6666666666666666, 'support': 2.0}, 'eval_incident_summary': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 1.0}, 'eval_micro avg': {'precision': 1.0, 'recall': 0.5294117647058824, 'f1-score': 0.6923076923076923, 'support': 17.0}, 'eval_macro avg': {'precision': 0.7142857142857143, 'recall': 0.5095238095238095, 'f1-score': 0.5768707482993197, 'support': 17.0}, 'eval_weighted avg': {'precision': 0.8235294117647058, 'recall': 0.5294117647058824, 'f1-score': 0.62296918767507, 'support': 17.0}, 'eval_samples avg': {'precision': 0.6923076923076923, 'recall': 0.6153846153846154, 'f1-score': 0.641025641025641, 'support': 17.0}, 'eval_runtime': 1.3777, 'eval_samples_per_second': 9.436, 'eval_steps_per_second': 0.726, 'epoch': 2.0}
Training model: ELECTRA Base

Some weights of ElectraForSequenceClassification were not initialized from the model checkpoint at google/electra-base-discriminator and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/usr/local/lib/python3.11/dist-packages/transformers/training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

Full Classification Report:
                precision    recall  f1-score   support

 armed_assault       0.00      0.00      0.00        41
        arrest       0.00      0.00      0.00        32
       bombing       0.00      0.00      0.00        10
infrastructure       0.00      0.00      0.00        14
     surrender       0.00      0.00      0.00         6
       seizure       0.00      0.00      0.00        21
     abduction       0.00      0.00      0.00        10

     micro avg       0.00      0.00      0.00       134
     macro avg       0.00      0.00      0.00       134
  weighted avg       0.00      0.00      0.00       134
   samples avg       0.00      0.00      0.00       134


Full Classification Report:
                precision    recall  f1-score   support

 armed_assault       0.97      0.78      0.86        41
        arrest       1.00      0.78      0.88        32
       bombing       0.00      0.00      0.00        10
infrastructure       0.00      0.00      0.00        14
     surrender       0.00      0.00      0.00         6
       seizure       0.00      0.00      0.00        21
     abduction       0.00      0.00      0.00        10

     micro avg       0.98      0.43      0.59       134
     macro avg       0.28      0.22      0.25       134
  weighted avg       0.54      0.43      0.47       134
   samples avg       0.51      0.45      0.47       134

Full Classification Report:
                precision    recall  f1-score   support

 armed_assault       0.00      0.00      0.00         5
        arrest       0.00      0.00      0.00         3
       bombing       0.00      0.00      0.00         2
infrastructure       0.00      0.00      0.00         3
     surrender       0.00      0.00      0.00         1
       seizure       0.00      0.00      0.00         2
     abduction       0.00      0.00      0.00         1

     micro avg       0.00      0.00      0.00        17
     macro avg       0.00      0.00      0.00        17
  weighted avg       0.00      0.00      0.00        17
   samples avg       0.00      0.00      0.00        17

Test Set Results: {'eval_loss': 0.45067039132118225, 'eval_hamming_loss': 0.18681318681318682, 'eval_subset_accuracy': 0.0, 'eval_arrest': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 5.0}, 'eval_bombing': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 3.0}, 'eval_infrastructure': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 2.0}, 'eval_surrender': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 3.0}, 'eval_seizure': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 1.0}, 'eval_abduction': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 2.0}, 'eval_incident_summary': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 1.0}, 'eval_micro avg': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 17.0}, 'eval_macro avg': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 17.0}, 'eval_weighted avg': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 17.0}, 'eval_samples avg': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 17.0}, 'eval_runtime': 0.496, 'eval_samples_per_second': 26.211, 'eval_steps_per_second': 2.016, 'epoch': 2.0}

=== DATA FRACTION: 0.25 (2480 rows) ===
Training model: BERT Base (cased)

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-cased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/usr/local/lib/python3.11/dist-packages/transformers/training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

Full Classification Report:
                precision    recall  f1-score   support

 armed_assault       0.94      0.86      0.90        77
        arrest       1.00      0.97      0.99        77
       bombing       0.75      0.10      0.18        29
infrastructure       0.88      0.78      0.82        18
     surrender       1.00      1.00      1.00        18
       seizure       0.93      0.75      0.83        51
     abduction       0.00      0.00      0.00         9

     micro avg       0.96      0.77      0.85       279
     macro avg       0.78      0.64      0.67       279
  weighted avg       0.90      0.77      0.81       279
   samples avg       0.83      0.78      0.79       279


Full Classification Report:
                precision    recall  f1-score   support

 armed_assault       0.94      0.86      0.90        77
        arrest       1.00      0.97      0.99        77
       bombing       0.92      0.83      0.87        29
infrastructure       0.93      0.78      0.85        18
     surrender       1.00      1.00      1.00        18
       seizure       0.91      0.96      0.93        51
     abduction       0.86      0.67      0.75         9

     micro avg       0.95      0.90      0.93       279
     macro avg       0.94      0.87      0.90       279
  weighted avg       0.95      0.90      0.92       279
   samples avg       0.95      0.92      0.93       279

Full Classification Report:
                precision    recall  f1-score   support

 armed_assault       1.00      0.80      0.89         5
        arrest       1.00      1.00      1.00         7
       bombing       0.00      0.00      0.00         2
infrastructure       1.00      0.50      0.67         2
     surrender       1.00      1.00      1.00         5
       seizure       1.00      0.86      0.92         7
     abduction       0.00      0.00      0.00         3

     micro avg       1.00      0.74      0.85        31
     macro avg       0.71      0.59      0.64        31
  weighted avg       0.84      0.74      0.78        31
   samples avg       0.80      0.74      0.76        31

Test Set Results: {'eval_loss': 0.19554996490478516, 'eval_hamming_loss': 0.045714285714285714, 'eval_subset_accuracy': 0.68, 'eval_arrest': {'precision': 1.0, 'recall': 0.8, 'f1-score': 0.8888888888888888, 'support': 5.0}, 'eval_bombing': {'precision': 1.0, 'recall': 1.0, 'f1-score': 1.0, 'support': 7.0}, 'eval_infrastructure': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 2.0}, 'eval_surrender': {'precision': 1.0, 'recall': 0.5, 'f1-score': 0.6666666666666666, 'support': 2.0}, 'eval_seizure': {'precision': 1.0, 'recall': 1.0, 'f1-score': 1.0, 'support': 5.0}, 'eval_abduction': {'precision': 1.0, 'recall': 0.8571428571428571, 'f1-score': 0.9230769230769231, 'support': 7.0}, 'eval_incident_summary': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 3.0}, 'eval_micro avg': {'precision': 1.0, 'recall': 0.7419354838709677, 'f1-score': 0.8518518518518519, 'support': 31.0}, 'eval_macro avg': {'precision': 0.7142857142857143, 'recall': 0.5938775510204081, 'f1-score': 0.6398046398046399, 'support': 31.0}, 'eval_weighted avg': {'precision': 0.8387096774193549, 'recall': 0.7419354838709677, 'f1-score': 0.7819134270747173, 'support': 31.0}, 'eval_samples avg': {'precision': 0.8, 'recall': 0.74, 'f1-score': 0.76, 'support': 31.0}, 'eval_runtime': 0.8167, 'eval_samples_per_second': 30.613, 'eval_steps_per_second': 2.449, 'epoch': 2.0}
Training model: ConfliBERT-scr-cased

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at snowood1/ConfliBERT-scr-cased and are newly initialized: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight', 'classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/usr/local/lib/python3.11/dist-packages/transformers/training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

Full Classification Report:
                precision    recall  f1-score   support

 armed_assault       0.94      0.83      0.88        77
        arrest       1.00      0.96      0.98        77
       bombing       0.92      0.76      0.83        29
infrastructure       1.00      0.83      0.91        18
     surrender       1.00      1.00      1.00        18
       seizure       0.93      0.84      0.89        51
     abduction       0.83      0.56      0.67         9

     micro avg       0.96      0.86      0.91       279
     macro avg       0.95      0.83      0.88       279
  weighted avg       0.96      0.86      0.91       279
   samples avg       0.93      0.89      0.90       279


Full Classification Report:
                precision    recall  f1-score   support

 armed_assault       0.96      0.84      0.90        77
        arrest       1.00      0.96      0.98        77
       bombing       0.93      0.90      0.91        29
infrastructure       1.00      0.89      0.94        18
     surrender       1.00      1.00      1.00        18
       seizure       0.93      1.00      0.96        51
     abduction       0.86      0.67      0.75         9

     micro avg       0.96      0.92      0.94       279
     macro avg       0.95      0.89      0.92       279
  weighted avg       0.96      0.92      0.94       279
   samples avg       0.96      0.94      0.94       279

Full Classification Report:
                precision    recall  f1-score   support

 armed_assault       1.00      1.00      1.00         5
        arrest       1.00      1.00      1.00         7
       bombing       1.00      1.00      1.00         2
infrastructure       1.00      1.00      1.00         2
     surrender       1.00      1.00      1.00         5
       seizure       1.00      1.00      1.00         7
     abduction       1.00      0.67      0.80         3

     micro avg       1.00      0.97      0.98        31
     macro avg       1.00      0.95      0.97        31
  weighted avg       1.00      0.97      0.98        31
   samples avg       1.00      0.98      0.99        31

Test Set Results: {'eval_loss': 0.1380385011434555, 'eval_hamming_loss': 0.005714285714285714, 'eval_subset_accuracy': 0.96, 'eval_arrest': {'precision': 1.0, 'recall': 1.0, 'f1-score': 1.0, 'support': 5.0}, 'eval_bombing': {'precision': 1.0, 'recall': 1.0, 'f1-score': 1.0, 'support': 7.0}, 'eval_infrastructure': {'precision': 1.0, 'recall': 1.0, 'f1-score': 1.0, 'support': 2.0}, 'eval_surrender': {'precision': 1.0, 'recall': 1.0, 'f1-score': 1.0, 'support': 2.0}, 'eval_seizure': {'precision': 1.0, 'recall': 1.0, 'f1-score': 1.0, 'support': 5.0}, 'eval_abduction': {'precision': 1.0, 'recall': 1.0, 'f1-score': 1.0, 'support': 7.0}, 'eval_incident_summary': {'precision': 1.0, 'recall': 0.6666666666666666, 'f1-score': 0.8, 'support': 3.0}, 'eval_micro avg': {'precision': 1.0, 'recall': 0.967741935483871, 'f1-score': 0.9836065573770492, 'support': 31.0}, 'eval_macro avg': {'precision': 1.0, 'recall': 0.9523809523809524, 'f1-score': 0.9714285714285714, 'support': 31.0}, 'eval_weighted avg': {'precision': 1.0, 'recall': 0.967741935483871, 'f1-score': 0.9806451612903225, 'support': 31.0}, 'eval_samples avg': {'precision': 1.0, 'recall': 0.98, 'f1-score': 0.9866666666666666, 'support': 31.0}, 'eval_runtime': 0.8015, 'eval_samples_per_second': 31.191, 'eval_steps_per_second': 2.495, 'epoch': 2.0}
Training model: RoBERTa Base

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at FacebookAI/roberta-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/usr/local/lib/python3.11/dist-packages/transformers/training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

Full Classification Report:
                precision    recall  f1-score   support

 armed_assault       0.97      0.83      0.90        77
        arrest       1.00      0.97      0.99        77
       bombing       0.92      0.76      0.83        29
infrastructure       0.85      0.94      0.89        18
     surrender       1.00      1.00      1.00        18
       seizure       0.90      0.86      0.88        51
     abduction       0.88      0.78      0.82         9

     micro avg       0.95      0.89      0.92       279
     macro avg       0.93      0.88      0.90       279
  weighted avg       0.95      0.89      0.92       279
   samples avg       0.94      0.91      0.91       279


Full Classification Report:
                precision    recall  f1-score   support

 armed_assault       0.96      0.84      0.90        77
        arrest       1.00      0.96      0.98        77
       bombing       0.93      0.86      0.89        29
infrastructure       0.89      0.89      0.89        18
     surrender       1.00      1.00      1.00        18
       seizure       0.91      0.98      0.94        51
     abduction       0.88      0.78      0.82         9

     micro avg       0.95      0.91      0.93       279
     macro avg       0.94      0.90      0.92       279
  weighted avg       0.95      0.91      0.93       279
   samples avg       0.95      0.93      0.93       279

Full Classification Report:
                precision    recall  f1-score   support

 armed_assault       1.00      0.80      0.89         5
        arrest       1.00      1.00      1.00         7
       bombing       0.67      1.00      0.80         2
infrastructure       1.00      0.50      0.67         2
     surrender       1.00      1.00      1.00         5
       seizure       1.00      0.71      0.83         7
     abduction       1.00      1.00      1.00         3

     micro avg       0.96      0.87      0.92        31
     macro avg       0.95      0.86      0.88        31
  weighted avg       0.98      0.87      0.91        31
   samples avg       0.92      0.88      0.89        31

Test Set Results: {'eval_loss': 0.1587548404932022, 'eval_hamming_loss': 0.02857142857142857, 'eval_subset_accuracy': 0.84, 'eval_arrest': {'precision': 1.0, 'recall': 0.8, 'f1-score': 0.8888888888888888, 'support': 5.0}, 'eval_bombing': {'precision': 1.0, 'recall': 1.0, 'f1-score': 1.0, 'support': 7.0}, 'eval_infrastructure': {'precision': 0.6666666666666666, 'recall': 1.0, 'f1-score': 0.8, 'support': 2.0}, 'eval_surrender': {'precision': 1.0, 'recall': 0.5, 'f1-score': 0.6666666666666666, 'support': 2.0}, 'eval_seizure': {'precision': 1.0, 'recall': 1.0, 'f1-score': 1.0, 'support': 5.0}, 'eval_abduction': {'precision': 1.0, 'recall': 0.7142857142857143, 'f1-score': 0.8333333333333334, 'support': 7.0}, 'eval_incident_summary': {'precision': 1.0, 'recall': 1.0, 'f1-score': 1.0, 'support': 3.0}, 'eval_micro avg': {'precision': 0.9642857142857143, 'recall': 0.8709677419354839, 'f1-score': 0.9152542372881356, 'support': 31.0}, 'eval_macro avg': {'precision': 0.9523809523809523, 'recall': 0.8591836734693877, 'f1-score': 0.8841269841269842, 'support': 31.0}, 'eval_weighted avg': {'precision': 0.9784946236559141, 'recall': 0.8709677419354839, 'f1-score': 0.910035842293907, 'support': 31.0}, 'eval_samples avg': {'precision': 0.92, 'recall': 0.88, 'f1-score': 0.8933333333333333, 'support': 31.0}, 'eval_runtime': 0.7303, 'eval_samples_per_second': 34.232, 'eval_steps_per_second': 2.739, 'epoch': 2.0}
Training model: DistilBERT (cased)

Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-cased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/usr/local/lib/python3.11/dist-packages/transformers/training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

Full Classification Report:
                precision    recall  f1-score   support

 armed_assault       0.86      0.88      0.87        77
        arrest       0.99      0.97      0.98        77
       bombing       0.00      0.00      0.00        29
infrastructure       1.00      0.50      0.67        18
     surrender       1.00      0.67      0.80        18
       seizure       0.85      0.33      0.48        51
     abduction       0.00      0.00      0.00         9

     micro avg       0.92      0.65      0.76       279
     macro avg       0.67      0.48      0.54       279
  weighted avg       0.79      0.65      0.69       279
   samples avg       0.79      0.69      0.72       279


Full Classification Report:
                precision    recall  f1-score   support

 armed_assault       0.94      0.83      0.88        77
        arrest       1.00      0.97      0.99        77
       bombing       0.90      0.66      0.76        29
infrastructure       0.94      0.83      0.88        18
     surrender       1.00      1.00      1.00        18
       seizure       0.91      0.80      0.85        51
     abduction       0.67      0.22      0.33         9

     micro avg       0.95      0.84      0.89       279
     macro avg       0.91      0.76      0.81       279
  weighted avg       0.94      0.84      0.88       279
   samples avg       0.91      0.87      0.88       279

Full Classification Report:
                precision    recall  f1-score   support

 armed_assault       0.67      0.80      0.73         5
        arrest       1.00      1.00      1.00         7
       bombing       0.00      0.00      0.00         2
infrastructure       0.00      0.00      0.00         2
     surrender       1.00      0.60      0.75         5
       seizure       1.00      0.57      0.73         7
     abduction       0.00      0.00      0.00         3

     micro avg       0.90      0.58      0.71        31
     macro avg       0.52      0.42      0.46        31
  weighted avg       0.72      0.58      0.63        31
   samples avg       0.72      0.60      0.64        31

Test Set Results: {'eval_loss': 0.24983830749988556, 'eval_hamming_loss': 0.08571428571428572, 'eval_subset_accuracy': 0.48, 'eval_arrest': {'precision': 0.6666666666666666, 'recall': 0.8, 'f1-score': 0.7272727272727273, 'support': 5.0}, 'eval_bombing': {'precision': 1.0, 'recall': 1.0, 'f1-score': 1.0, 'support': 7.0}, 'eval_infrastructure': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 2.0}, 'eval_surrender': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 2.0}, 'eval_seizure': {'precision': 1.0, 'recall': 0.6, 'f1-score': 0.75, 'support': 5.0}, 'eval_abduction': {'precision': 1.0, 'recall': 0.5714285714285714, 'f1-score': 0.7272727272727273, 'support': 7.0}, 'eval_incident_summary': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 3.0}, 'eval_micro avg': {'precision': 0.9, 'recall': 0.5806451612903226, 'f1-score': 0.7058823529411765, 'support': 31.0}, 'eval_macro avg': {'precision': 0.5238095238095238, 'recall': 0.4244897959183674, 'f1-score': 0.45779220779220786, 'support': 31.0}, 'eval_weighted avg': {'precision': 0.7204301075268816, 'recall': 0.5806451612903226, 'f1-score': 0.6282991202346041, 'support': 31.0}, 'eval_samples avg': {'precision': 0.72, 'recall': 0.6, 'f1-score': 0.64, 'support': 31.0}, 'eval_runtime': 0.4546, 'eval_samples_per_second': 54.997, 'eval_steps_per_second': 4.4, 'epoch': 2.0}
Training model: XLNet Base (cased)

Some weights of XLNetForSequenceClassification were not initialized from the model checkpoint at xlnet-base-cased and are newly initialized: ['logits_proj.bias', 'logits_proj.weight', 'sequence_summary.summary.bias', 'sequence_summary.summary.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/usr/local/lib/python3.11/dist-packages/transformers/training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

Full Classification Report:
                precision    recall  f1-score   support

 armed_assault       0.94      0.88      0.91        77
        arrest       1.00      0.96      0.98        77
       bombing       0.92      0.76      0.83        29
infrastructure       0.88      0.83      0.86        18
     surrender       1.00      1.00      1.00        18
       seizure       0.92      0.96      0.94        51
     abduction       0.88      0.78      0.82         9

     micro avg       0.95      0.91      0.93       279
     macro avg       0.93      0.88      0.91       279
  weighted avg       0.95      0.91      0.93       279
   samples avg       0.95      0.93      0.93       279


Full Classification Report:
                precision    recall  f1-score   support

 armed_assault       0.99      0.87      0.92        77
        arrest       1.00      0.96      0.98        77
       bombing       0.93      0.90      0.91        29
infrastructure       0.94      0.94      0.94        18
     surrender       1.00      1.00      1.00        18
       seizure       0.93      0.98      0.95        51
     abduction       0.88      0.78      0.82         9

     micro avg       0.97      0.93      0.95       279
     macro avg       0.95      0.92      0.93       279
  weighted avg       0.97      0.93      0.95       279
   samples avg       0.97      0.95      0.95       279

Full Classification Report:
                precision    recall  f1-score   support

 armed_assault       1.00      0.80      0.89         5
        arrest       1.00      1.00      1.00         7
       bombing       0.67      1.00      0.80         2
infrastructure       1.00      1.00      1.00         2
     surrender       1.00      1.00      1.00         5
       seizure       1.00      0.86      0.92         7
     abduction       1.00      1.00      1.00         3

     micro avg       0.97      0.94      0.95        31
     macro avg       0.95      0.95      0.94        31
  weighted avg       0.98      0.94      0.95        31
   samples avg       0.96      0.94      0.95        31

Test Set Results: {'eval_loss': 0.09270985424518585, 'eval_hamming_loss': 0.017142857142857144, 'eval_subset_accuracy': 0.92, 'eval_arrest': {'precision': 1.0, 'recall': 0.8, 'f1-score': 0.8888888888888888, 'support': 5.0}, 'eval_bombing': {'precision': 1.0, 'recall': 1.0, 'f1-score': 1.0, 'support': 7.0}, 'eval_infrastructure': {'precision': 0.6666666666666666, 'recall': 1.0, 'f1-score': 0.8, 'support': 2.0}, 'eval_surrender': {'precision': 1.0, 'recall': 1.0, 'f1-score': 1.0, 'support': 2.0}, 'eval_seizure': {'precision': 1.0, 'recall': 1.0, 'f1-score': 1.0, 'support': 5.0}, 'eval_abduction': {'precision': 1.0, 'recall': 0.8571428571428571, 'f1-score': 0.9230769230769231, 'support': 7.0}, 'eval_incident_summary': {'precision': 1.0, 'recall': 1.0, 'f1-score': 1.0, 'support': 3.0}, 'eval_micro avg': {'precision': 0.9666666666666667, 'recall': 0.9354838709677419, 'f1-score': 0.9508196721311475, 'support': 31.0}, 'eval_macro avg': {'precision': 0.9523809523809523, 'recall': 0.9510204081632653, 'f1-score': 0.9445665445665447, 'support': 31.0}, 'eval_weighted avg': {'precision': 0.9784946236559141, 'recall': 0.9354838709677419, 'f1-score': 0.9518059001929969, 'support': 31.0}, 'eval_samples avg': {'precision': 0.96, 'recall': 0.94, 'f1-score': 0.9466666666666665, 'support': 31.0}, 'eval_runtime': 2.7167, 'eval_samples_per_second': 9.202, 'eval_steps_per_second': 0.736, 'epoch': 2.0}
Training model: ELECTRA Base

Some weights of ElectraForSequenceClassification were not initialized from the model checkpoint at google/electra-base-discriminator and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/usr/local/lib/python3.11/dist-packages/transformers/training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

Full Classification Report:
                precision    recall  f1-score   support

 armed_assault       0.81      0.84      0.83        77
        arrest       0.96      0.96      0.96        77
       bombing       0.00      0.00      0.00        29
infrastructure       0.00      0.00      0.00        18
     surrender       0.00      0.00      0.00        18
       seizure       1.00      0.02      0.04        51
     abduction       0.00      0.00      0.00         9

     micro avg       0.89      0.50      0.64       279
     macro avg       0.40      0.26      0.26       279
  weighted avg       0.67      0.50      0.50       279
   samples avg       0.63      0.53      0.56       279


Full Classification Report:
                precision    recall  f1-score   support

 armed_assault       0.96      0.84      0.90        77
        arrest       0.97      0.95      0.96        77
       bombing       0.00      0.00      0.00        29
infrastructure       1.00      0.17      0.29        18
     surrender       0.00      0.00      0.00        18
       seizure       0.93      0.55      0.69        51
     abduction       0.00      0.00      0.00         9

     micro avg       0.96      0.61      0.74       279
     macro avg       0.55      0.36      0.40       279
  weighted avg       0.77      0.61      0.66       279
   samples avg       0.67      0.62      0.63       279

Full Classification Report:
                precision    recall  f1-score   support

 armed_assault       0.67      0.80      0.73         5
        arrest       0.88      1.00      0.93         7
       bombing       0.00      0.00      0.00         2
infrastructure       0.00      0.00      0.00         2
     surrender       0.00      0.00      0.00         5
       seizure       0.00      0.00      0.00         7
     abduction       0.00      0.00      0.00         3

     micro avg       0.79      0.35      0.49        31
     macro avg       0.22      0.26      0.24        31
  weighted avg       0.31      0.35      0.33        31
   samples avg       0.44      0.34      0.37        31

Test Set Results: {'eval_loss': 0.34195706248283386, 'eval_hamming_loss': 0.13142857142857142, 'eval_subset_accuracy': 0.24, 'eval_arrest': {'precision': 0.6666666666666666, 'recall': 0.8, 'f1-score': 0.7272727272727273, 'support': 5.0}, 'eval_bombing': {'precision': 0.875, 'recall': 1.0, 'f1-score': 0.9333333333333333, 'support': 7.0}, 'eval_infrastructure': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 2.0}, 'eval_surrender': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 2.0}, 'eval_seizure': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 5.0}, 'eval_abduction': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 7.0}, 'eval_incident_summary': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 3.0}, 'eval_micro avg': {'precision': 0.7857142857142857, 'recall': 0.3548387096774194, 'f1-score': 0.4888888888888889, 'support': 31.0}, 'eval_macro avg': {'precision': 0.2202380952380952, 'recall': 0.2571428571428572, 'f1-score': 0.23722943722943723, 'support': 31.0}, 'eval_weighted avg': {'precision': 0.3051075268817204, 'recall': 0.3548387096774194, 'f1-score': 0.3280547409579668, 'support': 31.0}, 'eval_samples avg': {'precision': 0.44, 'recall': 0.34, 'f1-score': 0.3733333333333333, 'support': 31.0}, 'eval_runtime': 0.8441, 'eval_samples_per_second': 29.618, 'eval_steps_per_second': 2.369, 'epoch': 2.0}

=== DATA FRACTION: 0.5 (4960 rows) ===
Training model: BERT Base (cased)

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-cased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/usr/local/lib/python3.11/dist-packages/transformers/training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

Full Classification Report:
                precision    recall  f1-score   support

 armed_assault       0.96      0.94      0.95       161
        arrest       0.99      0.98      0.98       138
       bombing       0.92      0.86      0.89        51
infrastructure       0.94      0.67      0.78        43
     surrender       0.98      1.00      0.99        44
       seizure       0.93      0.88      0.90       104
     abduction       0.90      0.82      0.86        22

     micro avg       0.96      0.91      0.93       563
     macro avg       0.94      0.88      0.91       563
  weighted avg       0.95      0.91      0.93       563
   samples avg       0.95      0.93      0.94       563


Full Classification Report:
                precision    recall  f1-score   support

 armed_assault       0.97      0.96      0.97       161
        arrest       0.99      0.98      0.98       138
       bombing       0.89      0.96      0.92        51
infrastructure       0.89      0.79      0.84        43
     surrender       0.98      1.00      0.99        44
       seizure       0.95      0.86      0.90       104
     abduction       0.90      0.82      0.86        22

     micro avg       0.96      0.93      0.94       563
     macro avg       0.94      0.91      0.92       563
  weighted avg       0.96      0.93      0.94       563
   samples avg       0.95      0.94      0.95       563

Full Classification Report:
                precision    recall  f1-score   support

 armed_assault       0.86      0.86      0.86        14
        arrest       1.00      1.00      1.00        15
       bombing       1.00      0.90      0.95        10
infrastructure       1.00      0.60      0.75         5
     surrender       1.00      1.00      1.00         5
       seizure       0.92      0.92      0.92        13
     abduction       1.00      0.50      0.67         4

     micro avg       0.95      0.88      0.91        66
     macro avg       0.97      0.83      0.88        66
  weighted avg       0.95      0.88      0.91        66
   samples avg       0.97      0.92      0.93        66

Test Set Results: {'eval_loss': 0.13026748597621918, 'eval_hamming_loss': 0.03142857142857143, 'eval_subset_accuracy': 0.8, 'eval_arrest': {'precision': 0.8571428571428571, 'recall': 0.8571428571428571, 'f1-score': 0.8571428571428571, 'support': 14.0}, 'eval_bombing': {'precision': 1.0, 'recall': 1.0, 'f1-score': 1.0, 'support': 15.0}, 'eval_infrastructure': {'precision': 1.0, 'recall': 0.9, 'f1-score': 0.9473684210526315, 'support': 10.0}, 'eval_surrender': {'precision': 1.0, 'recall': 0.6, 'f1-score': 0.75, 'support': 5.0}, 'eval_seizure': {'precision': 1.0, 'recall': 1.0, 'f1-score': 1.0, 'support': 5.0}, 'eval_abduction': {'precision': 0.9230769230769231, 'recall': 0.9230769230769231, 'f1-score': 0.9230769230769231, 'support': 13.0}, 'eval_incident_summary': {'precision': 1.0, 'recall': 0.5, 'f1-score': 0.6666666666666666, 'support': 4.0}, 'eval_micro avg': {'precision': 0.9508196721311475, 'recall': 0.8787878787878788, 'f1-score': 0.9133858267716536, 'support': 66.0}, 'eval_macro avg': {'precision': 0.968602825745683, 'recall': 0.8257456828885401, 'f1-score': 0.8777506954198684, 'support': 66.0}, 'eval_weighted avg': {'precision': 0.9545454545454546, 'recall': 0.8787878787878788, 'f1-score': 0.9074295587453481, 'support': 66.0}, 'eval_samples avg': {'precision': 0.97, 'recall': 0.9233333333333333, 'f1-score': 0.9326666666666666, 'support': 66.0}, 'eval_runtime': 1.5101, 'eval_samples_per_second': 33.111, 'eval_steps_per_second': 2.649, 'epoch': 2.0}
Training model: ConfliBERT-scr-cased

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at snowood1/ConfliBERT-scr-cased and are newly initialized: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight', 'classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/usr/local/lib/python3.11/dist-packages/transformers/training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

Full Classification Report:
                precision    recall  f1-score   support

 armed_assault       0.97      0.94      0.96       161
        arrest       0.99      0.95      0.97       138
       bombing       0.94      0.88      0.91        51
infrastructure       1.00      0.70      0.82        43
     surrender       0.98      1.00      0.99        44
       seizure       0.95      0.90      0.93       104
     abduction       1.00      0.82      0.90        22

     micro avg       0.97      0.91      0.94       563
     macro avg       0.98      0.89      0.92       563
  weighted avg       0.97      0.91      0.94       563
   samples avg       0.97      0.94      0.95       563

Full Classification Report:
                precision    recall  f1-score   support

 armed_assault       0.97      0.94      0.96       161
        arrest       0.99      0.98      0.98       138
       bombing       0.91      0.96      0.93        51
infrastructure       0.94      0.77      0.85        43
     surrender       0.98      1.00      0.99        44
       seizure       0.95      0.88      0.92       104
     abduction       1.00      0.86      0.93        22

     micro avg       0.97      0.93      0.95       563
     macro avg       0.96      0.91      0.94       563
  weighted avg       0.97      0.93      0.95       563
   samples avg       0.96      0.95      0.95       563

Full Classification Report:
                precision    recall  f1-score   support

 armed_assault       0.85      0.79      0.81        14
        arrest       1.00      1.00      1.00        15
       bombing       0.90      0.90      0.90        10
infrastructure       1.00      0.60      0.75         5
     surrender       1.00      1.00      1.00         5
       seizure       0.92      0.85      0.88        13
     abduction       1.00      0.75      0.86         4

     micro avg       0.93      0.86      0.90        66
     macro avg       0.95      0.84      0.89        66
  weighted avg       0.94      0.86      0.89        66
   samples avg       0.93      0.89      0.90        66

Test Set Results: {'eval_loss': 0.11042860150337219, 'eval_hamming_loss': 0.037142857142857144, 'eval_subset_accuracy': 0.78, 'eval_arrest': {'precision': 0.8461538461538461, 'recall': 0.7857142857142857, 'f1-score': 0.8148148148148148, 'support': 14.0}, 'eval_bombing': {'precision': 1.0, 'recall': 1.0, 'f1-score': 1.0, 'support': 15.0}, 'eval_infrastructure': {'precision': 0.9, 'recall': 0.9, 'f1-score': 0.9, 'support': 10.0}, 'eval_surrender': {'precision': 1.0, 'recall': 0.6, 'f1-score': 0.75, 'support': 5.0}, 'eval_seizure': {'precision': 1.0, 'recall': 1.0, 'f1-score': 1.0, 'support': 5.0}, 'eval_abduction': {'precision': 0.9166666666666666, 'recall': 0.8461538461538461, 'f1-score': 0.88, 'support': 13.0}, 'eval_incident_summary': {'precision': 1.0, 'recall': 0.75, 'f1-score': 0.8571428571428571, 'support': 4.0}, 'eval_micro avg': {'precision': 0.9344262295081968, 'recall': 0.8636363636363636, 'f1-score': 0.8976377952755905, 'support': 66.0}, 'eval_macro avg': {'precision': 0.9518315018315019, 'recall': 0.8402668759811617, 'f1-score': 0.8859939531368103, 'support': 66.0}, 'eval_weighted avg': {'precision': 0.9358003108003108, 'recall': 0.8636363636363636, 'f1-score': 0.8943330126663459, 'support': 66.0}, 'eval_samples avg': {'precision': 0.93, 'recall': 0.8933333333333333, 'f1-score': 0.8993333333333333, 'support': 66.0}, 'eval_runtime': 1.5276, 'eval_samples_per_second': 32.731, 'eval_steps_per_second': 2.618, 'epoch': 2.0}
Training model: RoBERTa Base

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at FacebookAI/roberta-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/usr/local/lib/python3.11/dist-packages/transformers/training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

Full Classification Report:
                precision    recall  f1-score   support

 armed_assault       0.96      0.94      0.95       161
        arrest       0.98      0.95      0.97       138
       bombing       0.92      0.92      0.92        51
infrastructure       0.97      0.67      0.79        43
     surrender       0.98      1.00      0.99        44
       seizure       0.92      0.88      0.90       104
     abduction       0.91      0.91      0.91        22

     micro avg       0.95      0.91      0.93       563
     macro avg       0.95      0.90      0.92       563
  weighted avg       0.95      0.91      0.93       563
   samples avg       0.96      0.94      0.94       563


Full Classification Report:
                precision    recall  f1-score   support

 armed_assault       0.96      0.94      0.95       161
        arrest       0.98      0.97      0.97       138
       bombing       0.91      0.96      0.93        51
infrastructure       0.89      0.72      0.79        43
     surrender       0.98      1.00      0.99        44
       seizure       0.93      0.88      0.91       104
     abduction       0.91      0.91      0.91        22

     micro avg       0.95      0.93      0.94       563
     macro avg       0.94      0.91      0.92       563
  weighted avg       0.95      0.93      0.94       563
   samples avg       0.96      0.95      0.95       563

Full Classification Report:
                precision    recall  f1-score   support

 armed_assault       0.93      0.93      0.93        14
        arrest       1.00      0.93      0.97        15
       bombing       1.00      1.00      1.00        10
infrastructure       1.00      0.60      0.75         5
     surrender       0.83      1.00      0.91         5
       seizure       0.92      0.92      0.92        13
     abduction       1.00      0.75      0.86         4

     micro avg       0.95      0.91      0.93        66
     macro avg       0.95      0.88      0.90        66
  weighted avg       0.96      0.91      0.93        66
   samples avg       0.96      0.93      0.94        66

Test Set Results: {'eval_loss': 0.11074775457382202, 'eval_hamming_loss': 0.025714285714285714, 'eval_subset_accuracy': 0.84, 'eval_arrest': {'precision': 0.9285714285714286, 'recall': 0.9285714285714286, 'f1-score': 0.9285714285714286, 'support': 14.0}, 'eval_bombing': {'precision': 1.0, 'recall': 0.9333333333333333, 'f1-score': 0.9655172413793104, 'support': 15.0}, 'eval_infrastructure': {'precision': 1.0, 'recall': 1.0, 'f1-score': 1.0, 'support': 10.0}, 'eval_surrender': {'precision': 1.0, 'recall': 0.6, 'f1-score': 0.75, 'support': 5.0}, 'eval_seizure': {'precision': 0.8333333333333334, 'recall': 1.0, 'f1-score': 0.9090909090909091, 'support': 5.0}, 'eval_abduction': {'precision': 0.9230769230769231, 'recall': 0.9230769230769231, 'f1-score': 0.9230769230769231, 'support': 13.0}, 'eval_incident_summary': {'precision': 1.0, 'recall': 0.75, 'f1-score': 0.8571428571428571, 'support': 4.0}, 'eval_micro avg': {'precision': 0.9523809523809523, 'recall': 0.9090909090909091, 'f1-score': 0.9302325581395349, 'support': 66.0}, 'eval_macro avg': {'precision': 0.9549973835688121, 'recall': 0.8764259549973836, 'f1-score': 0.9047713370373468, 'support': 66.0}, 'eval_weighted avg': {'precision': 0.9570707070707071, 'recall': 0.9090909090909091, 'f1-score': 0.9273755241623581, 'support': 66.0}, 'eval_samples avg': {'precision': 0.96, 'recall': 0.9333333333333332, 'f1-score': 0.936, 'support': 66.0}, 'eval_runtime': 1.4569, 'eval_samples_per_second': 34.318, 'eval_steps_per_second': 2.745, 'epoch': 2.0}
Training model: DistilBERT (cased)

Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-cased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/usr/local/lib/python3.11/dist-packages/transformers/training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

Full Classification Report:
                precision    recall  f1-score   support

 armed_assault       0.94      0.91      0.93       161
        arrest       0.99      0.97      0.98       138
       bombing       0.94      0.86      0.90        51
infrastructure       0.94      0.67      0.78        43
     surrender       0.98      0.93      0.95        44
       seizure       0.94      0.84      0.88       104
     abduction       1.00      0.32      0.48        22

     micro avg       0.96      0.87      0.91       563
     macro avg       0.96      0.79      0.84       563
  weighted avg       0.96      0.87      0.90       563
   samples avg       0.93      0.90      0.91       563


Full Classification Report:
                precision    recall  f1-score   support

 armed_assault       0.95      0.91      0.93       161
        arrest       0.99      0.97      0.98       138
       bombing       0.91      0.96      0.93        51
infrastructure       1.00      0.74      0.85        43
     surrender       0.98      0.98      0.98        44
       seizure       0.94      0.86      0.89       104
     abduction       0.94      0.73      0.82        22

     micro avg       0.96      0.90      0.93       563
     macro avg       0.96      0.88      0.91       563
  weighted avg       0.96      0.90      0.93       563
   samples avg       0.95      0.93      0.93       563

Full Classification Report:
                precision    recall  f1-score   support

 armed_assault       0.91      0.71      0.80        14
        arrest       1.00      1.00      1.00        15
       bombing       1.00      0.90      0.95        10
infrastructure       1.00      0.60      0.75         5
     surrender       1.00      1.00      1.00         5
       seizure       0.92      0.85      0.88        13
     abduction       1.00      0.25      0.40         4

     micro avg       0.96      0.82      0.89        66
     macro avg       0.98      0.76      0.83        66
  weighted avg       0.96      0.82      0.87        66
   samples avg       0.95      0.88      0.90        66

Test Set Results: {'eval_loss': 0.14501211047172546, 'eval_hamming_loss': 0.04, 'eval_subset_accuracy': 0.78, 'eval_arrest': {'precision': 0.9090909090909091, 'recall': 0.7142857142857143, 'f1-score': 0.8, 'support': 14.0}, 'eval_bombing': {'precision': 1.0, 'recall': 1.0, 'f1-score': 1.0, 'support': 15.0}, 'eval_infrastructure': {'precision': 1.0, 'recall': 0.9, 'f1-score': 0.9473684210526315, 'support': 10.0}, 'eval_surrender': {'precision': 1.0, 'recall': 0.6, 'f1-score': 0.75, 'support': 5.0}, 'eval_seizure': {'precision': 1.0, 'recall': 1.0, 'f1-score': 1.0, 'support': 5.0}, 'eval_abduction': {'precision': 0.9166666666666666, 'recall': 0.8461538461538461, 'f1-score': 0.88, 'support': 13.0}, 'eval_incident_summary': {'precision': 1.0, 'recall': 0.25, 'f1-score': 0.4, 'support': 4.0}, 'eval_micro avg': {'precision': 0.9642857142857143, 'recall': 0.8181818181818182, 'f1-score': 0.8852459016393442, 'support': 66.0}, 'eval_macro avg': {'precision': 0.9751082251082251, 'recall': 0.7586342229199372, 'f1-score': 0.8253383458646617, 'support': 66.0}, 'eval_weighted avg': {'precision': 0.9643021120293848, 'recall': 0.8181818181818182, 'f1-score': 0.8706618819776715, 'support': 66.0}, 'eval_samples avg': {'precision': 0.95, 'recall': 0.8766666666666666, 'f1-score': 0.8966666666666666, 'support': 66.0}, 'eval_runtime': 0.8014, 'eval_samples_per_second': 62.39, 'eval_steps_per_second': 4.991, 'epoch': 2.0}
Training model: XLNet Base (cased)

Some weights of XLNetForSequenceClassification were not initialized from the model checkpoint at xlnet-base-cased and are newly initialized: ['logits_proj.bias', 'logits_proj.weight', 'sequence_summary.summary.bias', 'sequence_summary.summary.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/usr/local/lib/python3.11/dist-packages/transformers/training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

Full Classification Report:
                precision    recall  f1-score   support

 armed_assault       0.94      0.94      0.94       161
        arrest       0.98      0.97      0.97       138
       bombing       0.94      0.94      0.94        51
infrastructure       0.97      0.74      0.84        43
     surrender       0.98      1.00      0.99        44
       seizure       0.95      0.87      0.90       104
     abduction       0.94      0.73      0.82        22

     micro avg       0.96      0.91      0.94       563
     macro avg       0.96      0.88      0.92       563
  weighted avg       0.96      0.91      0.93       563
   samples avg       0.96      0.94      0.94       563


Full Classification Report:
                precision    recall  f1-score   support

 armed_assault       0.97      0.96      0.96       161
        arrest       0.99      0.99      0.99       138
       bombing       0.88      0.98      0.93        51
infrastructure       0.89      0.74      0.81        43
     surrender       0.98      1.00      0.99        44
       seizure       0.94      0.88      0.91       104
     abduction       0.95      0.86      0.90        22

     micro avg       0.95      0.94      0.94       563
     macro avg       0.94      0.92      0.93       563
  weighted avg       0.95      0.94      0.94       563
   samples avg       0.96      0.95      0.95       563

Full Classification Report:
                precision    recall  f1-score   support

 armed_assault       0.81      0.93      0.87        14
        arrest       1.00      1.00      1.00        15
       bombing       1.00      0.90      0.95        10
infrastructure       1.00      0.60      0.75         5
     surrender       1.00      1.00      1.00         5
       seizure       0.92      0.92      0.92        13
     abduction       1.00      0.75      0.86         4

     micro avg       0.94      0.91      0.92        66
     macro avg       0.96      0.87      0.91        66
  weighted avg       0.95      0.91      0.92        66
   samples avg       0.96      0.94      0.94        66

Test Set Results: {'eval_loss': 0.0860959067940712, 'eval_hamming_loss': 0.02857142857142857, 'eval_subset_accuracy': 0.8, 'eval_arrest': {'precision': 0.8125, 'recall': 0.9285714285714286, 'f1-score': 0.8666666666666667, 'support': 14.0}, 'eval_bombing': {'precision': 1.0, 'recall': 1.0, 'f1-score': 1.0, 'support': 15.0}, 'eval_infrastructure': {'precision': 1.0, 'recall': 0.9, 'f1-score': 0.9473684210526315, 'support': 10.0}, 'eval_surrender': {'precision': 1.0, 'recall': 0.6, 'f1-score': 0.75, 'support': 5.0}, 'eval_seizure': {'precision': 1.0, 'recall': 1.0, 'f1-score': 1.0, 'support': 5.0}, 'eval_abduction': {'precision': 0.9230769230769231, 'recall': 0.9230769230769231, 'f1-score': 0.9230769230769231, 'support': 13.0}, 'eval_incident_summary': {'precision': 1.0, 'recall': 0.75, 'f1-score': 0.8571428571428571, 'support': 4.0}, 'eval_micro avg': {'precision': 0.9375, 'recall': 0.9090909090909091, 'f1-score': 0.9230769230769231, 'support': 66.0}, 'eval_macro avg': {'precision': 0.9622252747252747, 'recall': 0.8716640502354789, 'f1-score': 0.9063221239912969, 'support': 66.0}, 'eval_weighted avg': {'precision': 0.9450757575757576, 'recall': 0.9090909090909091, 'f1-score': 0.9209937723095618, 'support': 66.0}, 'eval_samples avg': {'precision': 0.9633333333333334, 'recall': 0.9433333333333332, 'f1-score': 0.9386666666666666, 'support': 66.0}, 'eval_runtime': 5.4107, 'eval_samples_per_second': 9.241, 'eval_steps_per_second': 0.739, 'epoch': 2.0}
Training model: ELECTRA Base

Some weights of ElectraForSequenceClassification were not initialized from the model checkpoint at google/electra-base-discriminator and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/usr/local/lib/python3.11/dist-packages/transformers/training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

Full Classification Report:
                precision    recall  f1-score   support

 armed_assault       0.90      0.94      0.92       161
        arrest       0.99      0.95      0.97       138
       bombing       0.95      0.78      0.86        51
infrastructure       0.96      0.60      0.74        43
     surrender       1.00      0.95      0.98        44
       seizure       0.91      0.84      0.87       104
     abduction       0.00      0.00      0.00        22

     micro avg       0.94      0.85      0.89       563
     macro avg       0.82      0.72      0.76       563
  weighted avg       0.91      0.85      0.87       563
   samples avg       0.92      0.88      0.89       563

In [ ]:
import os


def save_to_drive(df, filename, folder_name="actiontype"):
    base_path = "/content/drive/MyDrive/SATP_data/paper/exp"
    drive_path = os.path.join(base_path, folder_name)

    # Create the folder if it doesn't exist
    if not os.path.exists(drive_path):
        os.makedirs(drive_path)

    filepath = os.path.join(drive_path, filename)
    df.to_csv(filepath, index=False)
    print(f"✅ DataFrame saved to: {filepath}")

save_to_drive(final_results_df, "exp_actiontype_results.csv")